import { existsSync, readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

const chartDemoViewUrl = new URL('../src/views/ChartDemoView.vue', import.meta.url)
const appEChartUrl = new URL('../src/components/common/AppEChart.vue', import.meta.url)
const routerSource = readFileSync(new URL('../src/router/index.ts', import.meta.url), 'utf-8')
const navigationSource = readFileSync(new URL('../src/data/navigation.ts', import.meta.url), 'utf-8')

describe('chart demo source', () => {
  it('adds a visible chart demo route and navigation entry', () => {
    expect(routerSource).toContain("import ChartDemoView from '../views/ChartDemoView.vue'")
    expect(routerSource).toContain("path: 'chart-demo'")
    expect(routerSource).toContain("component: ChartDemoView")
    expect(routerSource).toContain("title: '图表 Demo'")
    expect(routerSource).toMatch(/title: '图表 Demo',[\s\S]*sectionKey: 'chart-demo',[\s\S]*sectionTitle: '图表 Demo',[\s\S]*hideBreadcrumb: true/)
    expect(navigationSource).toContain("key: 'chart-demo'")
    expect(navigationSource).toContain("title: '图表 Demo'")
    expect(navigationSource).toContain("path: '/chart-demo'")
  })

  it('provides a generic reusable ECharts wrapper for demo cards', () => {
    expect(existsSync(appEChartUrl)).toBe(true)

    const componentSource = readFileSync(appEChartUrl, 'utf-8')
    expect(componentSource).toContain("import VChart from 'vue-echarts'")
    expect(componentSource).toContain("import type { EChartsOption, SetOptionOpts } from 'echarts'")
    expect(componentSource).toContain('updateOptions?: SetOptionOpts')
    expect(componentSource).toContain(':update-options="updateOptions"')
    expect(componentSource).toContain('BarChart')
    expect(componentSource).toContain('PieChart')
    expect(componentSource).toContain('RadarChart')
    expect(componentSource).toContain('FunnelChart')
    expect(componentSource).toContain('GaugeChart')
    expect(componentSource).toContain('HeatmapChart')
    expect(componentSource).toContain('TreemapChart')
    expect(componentSource).toContain('SankeyChart')
    expect(componentSource).toContain('GraphChart')
    expect(componentSource).toContain('autoresize')
    expect(componentSource).toContain('class="app-e-chart"')
  })

  it('uses the shared filter components so the page matches workbench patterns', () => {
    expect(existsSync(chartDemoViewUrl)).toBe(true)

    const viewSource = readFileSync(chartDemoViewUrl, 'utf-8')
    expect(viewSource).toContain("import AppEChart from '../components/common/AppEChart.vue'")
    expect(viewSource).toContain("import { Message } from '@arco-design/web-vue'")
    expect(viewSource).toContain("import { IconCopy, IconShareExternal } from '@arco-design/web-vue/es/icon'")
    expect(viewSource).toContain("import QueryActionBar from '../components/common/QueryActionBar.vue'")
    expect(viewSource).toContain("import QueryFilterItem from '../components/common/QueryFilterItem.vue'")
    expect(viewSource).toContain("import QueryFilterPanel from '../components/common/QueryFilterPanel.vue'")
    expect(viewSource).toContain("import '../components/sales/salesWorkbench.css'")
    expect(viewSource).toContain('class="sales-workbench chart-demo-workbench"')
    expect(viewSource).toContain('<QueryFilterPanel>')
    expect(viewSource).toContain('<QueryFilterItem')
    expect(viewSource).toContain('<QueryActionBar>')
    expect(viewSource).toContain('filteredDemos')
    expect(viewSource).toContain('resetFilters')
  })

  it('links to the official gallery and makes demo ids easy to reuse', () => {
    expect(existsSync(chartDemoViewUrl)).toBe(true)

    const viewSource = readFileSync(chartDemoViewUrl, 'utf-8')
    expect(viewSource).toContain("const chartExampleUrl = 'https://echarts.apache.org/examples/zh/index.html'")
    expect(viewSource).toContain('href="chartExampleUrl"')
    expect(viewSource).not.toContain('target="_blank"')
    expect(viewSource).toContain('查看更多图表示例')
    expect(viewSource).toContain('const copyDemoId = async (id: string) =>')
    expect(viewSource).toContain('navigator.clipboard.writeText(id)')
    expect(viewSource).toContain("Message.success(`已复制 ${id}`)")
    expect(viewSource).toContain('@click="copyDemoId(demo.id)"')
    expect(viewSource).toContain('<IconCopy />')
  })

  it('shows expanded chart choices with stable ids users can reference', () => {
    expect(existsSync(chartDemoViewUrl)).toBe(true)

    const viewSource = readFileSync(chartDemoViewUrl, 'utf-8')
    expect(viewSource).toContain("id: 'line-trend'")
    expect(viewSource).toContain("id: 'multi-line'")
    expect(viewSource).toContain("id: 'dual-axis'")
    expect(viewSource).toContain("id: 'area-trend'")
    expect(viewSource).toContain("id: 'stacked-area'")
    expect(viewSource).toContain("id: 'bar-compare'")
    expect(viewSource).toContain("id: 'horizontal-bar'")
    expect(viewSource).toContain("id: 'stacked-bar'")
    expect(viewSource).toContain("id: 'waterfall-profit'")
    expect(viewSource).toContain("id: 'donut-share'")
    expect(viewSource).toContain("id: 'rose-pie'")
    expect(viewSource).toContain("id: 'treemap-category'")
    expect(viewSource).toContain("id: 'radar-score'")
    expect(viewSource).toContain("id: 'funnel-conversion'")
    expect(viewSource).toContain("id: 'gauge-progress'")
    expect(viewSource).toContain("id: 'heatmap-calendar'")
    expect(viewSource).toContain("id: 'scatter-correlation'")
    expect(viewSource).toContain("id: 'bubble-scatter'")
    expect(viewSource).toContain("id: 'sankey-flow'")
    expect(viewSource).toContain("id: 'graph-relation'")
    expect(viewSource).toContain('v-for="demo in filteredDemos"')
  })

  it('formats hover tooltips so chart nodes show their data', () => {
    expect(existsSync(chartDemoViewUrl)).toBe(true)

    const viewSource = readFileSync(chartDemoViewUrl, 'utf-8')
    expect(viewSource).toContain('const formatTooltipValue = (value: unknown): string =>')
    expect(viewSource).toContain('const formatChartTooltip = (params: unknown) =>')
    expect(viewSource).toContain('const axisTooltip = { trigger: \'axis\', confine: true, formatter: formatChartTooltip }')
    expect(viewSource).toContain('const itemTooltip = { trigger: \'item\', confine: true, formatter: formatChartTooltip }')
    expect(viewSource).toContain('tooltip: axisTooltip')
    expect(viewSource).toContain('tooltip: itemTooltip')
    expect(viewSource).toContain('tooltip: { ...itemTooltip, position: \'top\' }')
  })
})
