import { existsSync, readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

const workbenchPath = new URL('../src/components/products/ProductMetadataWorkbench.vue', import.meta.url)
const stylePath = new URL('../src/components/products/productMetadata.css', import.meta.url)

const readIfExists = (url: URL) => existsSync(url) ? readFileSync(url, 'utf-8') : ''

const workbenchSource = readIfExists(workbenchPath)
const styleSource = readIfExists(stylePath)

describe('product metadata workbench source', () => {
  it('uses a shared configurable-table workbench for brand and category pages', () => {
    expect(workbenchSource).toContain("import ConfigurableDataTable from '../common/ConfigurableDataTable.vue'")
    expect(workbenchSource).toContain('ProductMetadataPageKey')
    expect(workbenchSource).toContain('productMetadataPageConfigs[props.pageKey]')
    expect(workbenchSource).toContain('v-model:settings-visible="settingsVisible"')
    expect(workbenchSource).toContain('wrapper-class="product-metadata-table"')
  })

  it('reuses the common workbench components around the metadata table', () => {
    for (const snippet of [
      "import QueryFilterPanel from '../common/QueryFilterPanel.vue'",
      "import QueryFilterItem from '../common/QueryFilterItem.vue'",
      "import QueryActionBar from '../common/QueryActionBar.vue'",
      '<QueryFilterPanel>',
      '<QueryFilterItem',
      '<QueryActionBar>',
      ':table-class="tableClass"',
    ]) {
      expect(workbenchSource).toContain(snippet)
    }

    expect(workbenchSource).not.toContain("import MetricSummaryStrip from '../common/MetricSummaryStrip.vue'")
    expect(workbenchSource).not.toContain('<MetricSummaryStrip')
    expect(workbenchSource).not.toContain('summaryCards')
    expect(workbenchSource).not.toContain('<section class="product-metadata-summary">')
    expect(workbenchSource).not.toContain('<section class="product-metadata-filter">')
  })

  it('renders add buttons and modal fields matching the provided prototypes', () => {
    expect(workbenchSource).toContain('openCreateModal')
    expect(workbenchSource).toContain('openEditModal(record)')
    expect(workbenchSource).toContain('openImportCategoryModal')
    expect(workbenchSource).toContain('导入新增品类')
    expect(workbenchSource).toMatch(/v-if="pageKey === 'category'"\s+type="outline"\s+class="action-button"/)
    expect(workbenchSource).toContain('下载导入模板')
    expect(workbenchSource).toContain('2025.10 更新')
    expect(workbenchSource).toContain("import type { FileItem, RequestOption, UploadRequest } from '@arco-design/web-vue/es/upload/interfaces'")
    expect(workbenchSource).toContain('const categoryImportFileList = ref<FileItem[]>([])')
    expect(workbenchSource).toContain('const handleCategoryImportRequest = (option: RequestOption): UploadRequest =>')
    expect(workbenchSource).toContain('const validateCategoryImportFile = (file: File) =>')
    expect(workbenchSource).toContain('const handleCategoryImportUploadChange = (fileList: FileItem[]) =>')
    expect(workbenchSource).toContain('const handleCategoryImportExceedLimit = () =>')
    expect(workbenchSource).toContain('<a-upload')
    expect(workbenchSource).toContain('v-model:file-list="categoryImportFileList"')
    expect(workbenchSource).toContain("accept=\".xls,.xlsx\"")
    expect(workbenchSource).toContain(':limit="1"')
    expect(workbenchSource).toContain(':show-upload-button="{ showOnExceedLimit: true }"')
    expect(workbenchSource).toContain(':custom-request="handleCategoryImportRequest"')
    expect(workbenchSource).toContain(':on-before-upload="validateCategoryImportFile"')
    expect(workbenchSource).toContain('@change="handleCategoryImportUploadChange"')
    expect(workbenchSource).toContain('@exceed-limit="handleCategoryImportExceedLimit"')
    expect(workbenchSource).toContain('<template #upload-button>')
    expect(workbenchSource).toContain('点击导入')
    expect(workbenchSource).toContain('<span class="metadata-import-upload-row">')
    expect(workbenchSource).toMatch(/点击导入\s+<\/a-button>\s+<a-link class="metadata-import-template-link" @click\.stop="downloadCategoryImportTemplate">/)
    expect(workbenchSource).toMatch(/<\/a-link>\s+<span class="metadata-import-date">模板版本：2025\.10 更新<\/span>\s+<\/span>/)
    expect(workbenchSource).toContain('已成功导入')
    expect(workbenchSource).toContain('支持导入格式为 xls/xlsx 的文件')
    expect(workbenchSource).not.toContain('tip="支持导入格式为 xls/xlsx 的文件，导入文件不能超过1000行"')
    expect(workbenchSource).toContain('模板中的表头不可更改，不能删除')
    expect(workbenchSource).toContain('导入文件不能超过1000行')
    expect(workbenchSource).not.toContain('metadata-import-upload-card')
    expect(workbenchSource).not.toContain('metadata-import-file-card')
    expect(workbenchSource).not.toContain('重新选择')
    expect(workbenchSource).toContain(':footer="false"')
    expect(workbenchSource).toContain('modalMode')
    expect(workbenchSource).toContain('editingRecordId')
    expect(workbenchSource).toContain('activeModalTitle')
    expect(workbenchSource).toContain('activeModalFields')
    expect(workbenchSource).toContain('config.primaryAction')
    expect(workbenchSource).toContain('IconExport')
    expect(workbenchSource).toContain('aria-label="导出"')
    expect(workbenchSource).toContain('<icon-export />')
    expect(workbenchSource).toContain('<a-modal')
    expect(workbenchSource).toContain('simple')
    expect(workbenchSource).toContain('width="600px"')
    expect(workbenchSource).toContain('modal-class="metadata-simple-modal"')
    expect(workbenchSource).toContain('title-align="start"')
    expect(workbenchSource).toContain('align-center')
    expect(workbenchSource).toContain(':on-before-ok="submitMetadataModal"')
    expect(workbenchSource).toContain(':title="activeModalTitle"')
    expect(workbenchSource).not.toContain('width="700px"')
    expect(workbenchSource).not.toContain('width="800px"')
    expect(workbenchSource).not.toContain('modal-class="product-metadata-modal"')
    expect(workbenchSource).not.toContain('metadata-modal-footer')
    expect(workbenchSource).toContain('<a-form')
    expect(workbenchSource).toContain(':model="formState"')
    expect(workbenchSource).toContain('layout="horizontal"')
    expect(workbenchSource).toContain(':label-col-props="{ span: 5 }"')
    expect(workbenchSource).toContain(':wrapper-col-props="{ span: 19 }"')
    expect(workbenchSource).toContain('<a-form-item')
    expect(workbenchSource).toContain(':field="field.key"')
    expect(workbenchSource).toContain(':label="field.label"')
    expect(workbenchSource).toContain(':required="field.required"')
    expect(workbenchSource).toContain('class="metadata-modal-content"')
    expect(workbenchSource).toContain(':disabled="isFieldDisabled(field)"')
    expect(workbenchSource).toContain('show-word-limit')
    expect(workbenchSource).toContain(':max-length="field.maxLength"')
    expect(workbenchSource).toContain("field.key === 'shortCode'")
    expect(workbenchSource).toContain("field.key === 'status'")
    expect(workbenchSource).toContain('新增品牌资料')
    expect(workbenchSource).toContain('config.value.editModalTitle')
    expect(workbenchSource).toContain('添加品类')
    expect(workbenchSource).not.toContain('<span class="page-desc">{{ config.description }}</span>')
  })

  it('supports category bulk selection and inline status switching', () => {
    expect(workbenchSource).toContain('const selectedRowKeys = ref')
    expect(workbenchSource).toContain('const moveCategoryModalVisible = ref(false)')
    expect(workbenchSource).toContain('const moveTargetCategory = ref')
    expect(workbenchSource).toContain('productMetadataMoveCategoryOptions')
    expect(workbenchSource).toContain('const metadataRowSelection = computed')
    expect(workbenchSource).toContain("props.pageKey === 'category'")
    expect(workbenchSource).toContain("filters.status")
    expect(workbenchSource).toContain('<QueryFilterItem label="状态"')
    expect(workbenchSource).toContain('productMetadataStatusOptions')
    expect(workbenchSource).toContain('option === \'启用\' ? \'开启\' : option')
    expect(workbenchSource).not.toContain('<a-button type="primary" class="action-button" @click="applyFilters">查询</a-button>')
    expect(workbenchSource).toContain(':row-selection="metadataRowSelection"')
    expect(workbenchSource).toContain('v-model:selected-keys="selectedRowKeys"')
    expect(workbenchSource).toContain('<a-switch')
    expect(workbenchSource).toContain('checked-value="启用"')
    expect(workbenchSource).toContain('unchecked-value="停用"')
    expect(workbenchSource).not.toContain('checked-text="开启"')
    expect(workbenchSource).not.toContain('unchecked-text="停用"')
    expect(workbenchSource).toContain('@change="toggleRowStatus(record, $event)"')
    expect(workbenchSource).toContain('class="metadata-bulk-action-bar"')
    expect(workbenchSource).toContain('已选 <span>{{ selectedRowKeys.length }}</span> / {{ filteredRows.length }} 条')
    expect(workbenchSource).toContain('取消选择')
    expect(workbenchSource).toContain('移动品类')
    expect(workbenchSource).toContain('批量删除')
    expect(workbenchSource).toContain('<a-button @click="moveSelectedCategories">移动品类</a-button>')
    expect(workbenchSource).toContain('<a-button @click="deleteSelectedCategories">批量删除</a-button>')
    expect(workbenchSource).not.toContain('批量绑定')
    expect(workbenchSource).not.toContain('bindSelectedCategories')
    expect(workbenchSource).not.toContain('bindCategoryDrawerVisible')
    expect(workbenchSource).not.toContain('selectedBindProductKeys')
    expect(workbenchSource).not.toContain('metadata-bind-drawer')
    expect(workbenchSource).not.toContain('v-model="bindTargetSite"')
    expect(workbenchSource).not.toContain('label="绑定站点"')
    expect(workbenchSource).toContain('Modal.confirm')
    expect(workbenchSource).toContain("title: '确认删除品类'")
    expect(workbenchSource).toContain("titleAlign: 'start'")
    expect(workbenchSource).toContain("modalClass: 'metadata-confirm-modal'")
    expect(workbenchSource).toContain("okText: '删除'")
    expect(workbenchSource).toContain("cancelText: '取消'")
    expect(workbenchSource).toContain('导出所选品类')
    expect(workbenchSource).toContain('<a-button @click="exportSelectedCategories">导出所选品类</a-button>')
    expect(workbenchSource).toContain('exportSelectedCategories')
    expect(workbenchSource).toContain('title="移动品类"')
    expect(workbenchSource).toContain('width="600px"')
    expect(workbenchSource).toContain('<a-cascader')
    expect(workbenchSource).toContain('allow-search')
    expect(workbenchSource).toContain(':options="productMetadataMoveCategoryOptions"')
    expect(workbenchSource).toContain(':on-before-ok="submitMoveCategoryModal"')
    expect(styleSource).toContain('width: 40px;')
    expect(styleSource).toContain('height: var(--workspace-control-height')
    expect(styleSource).toContain('.metadata-move-category-cascader')
    expect(styleSource).not.toContain('.metadata-bind-drawer')
    expect(styleSource).not.toContain('.metadata-bind-toolbar')
    expect(styleSource).not.toContain('.metadata-bind-product-cell')
    expect(styleSource).toContain('.metadata-confirm-modal.arco-modal-simple .arco-modal-footer')
    expect(styleSource).toContain('text-align: right')
    expect(styleSource).toContain('.metadata-import-upload')
    expect(styleSource).toMatch(/\.metadata-import-action-panel\s*{[^}]*justify-content: flex-start;/)
    expect(styleSource).not.toMatch(/\.metadata-import-action-panel\s*{[^}]*justify-content: space-between;/)
    expect(styleSource).toMatch(/\.metadata-import-action-main\s*{[^}]*width: 100%;[^}]*overflow-x: hidden;/)
    expect(styleSource).toMatch(/\.metadata-import-upload\s*{[^}]*width: 100%;[^}]*max-width: 100%;/)
    expect(styleSource).toMatch(/\.metadata-import-upload \.arco-upload-list\s*{[^}]*min-width: 0;[^}]*max-width: 100%;[^}]*overflow-x: hidden;/)
    expect(styleSource).toMatch(/\.metadata-import-upload \.arco-upload-list-item-name-text\s*{[^}]*text-overflow: ellipsis;/)
    expect(styleSource).not.toContain('.metadata-import-upload-card')
    expect(styleSource).not.toContain('.metadata-import-file-card')
    expect(styleSource).not.toContain('.metadata-import-file-input')
    expect(styleSource).not.toContain('.metadata-import-upload .arco-upload-tip')
  })

  it('keeps metadata names as simple default text without secondary copy', () => {
    expect(workbenchSource).toContain('class="metadata-name-cell"')
    expect(workbenchSource).toContain('{{ record.name }}')
    expect(workbenchSource).not.toContain('<strong>{{ record.name }}</strong>')
    expect(workbenchSource).not.toContain('<small>{{ record.createdBy }}')
    expect(workbenchSource).not.toContain("record.kind === 'brand' ? '品牌'")
    expect(styleSource).not.toContain('.metadata-name-cell strong')
    expect(styleSource).not.toContain('.metadata-name-cell small')
  })

  it('connects simple wrapper views to the shared workbench', () => {
    const brandView = readFileSync(new URL('../src/views/ProductBrandView.vue', import.meta.url), 'utf-8')
    const categoryView = readFileSync(new URL('../src/views/ProductCategoryView.vue', import.meta.url), 'utf-8')

    expect(brandView).toContain("import ProductMetadataWorkbench from '../components/products/ProductMetadataWorkbench.vue'")
    expect(brandView).toContain('<ProductMetadataWorkbench page-key="brand" />')
    expect(categoryView).toContain('<ProductMetadataWorkbench page-key="category" />')
  })

  it('keeps metadata pages adaptive and visually aligned with product management', () => {
    expect(workbenchSource).toContain("import '../sales/salesWorkbench.css'")
    expect(styleSource).toContain('.product-metadata-page')
    expect(styleSource).toContain('--workspace-color-control-border')
    expect(styleSource).toContain('--workspace-control-height')
    expect(styleSource).toMatch(/\.metadata-code-cell\s*{[^}]*color: var\(--metadata-color-text\);[^}]*font-weight: 400;/)
    expect(styleSource).not.toMatch(/\.metadata-code-cell\s*{[^}]*color: var\(--metadata-color-primary\);/)
    expect(styleSource).toContain('height: 40px;')
    expect(styleSource).toContain('.metadata-modal-content')
    expect(styleSource).toContain('.metadata-table-footer-row')
    expect(styleSource).toContain('.metadata-bulk-action-bar')
    expect(styleSource).toContain('.metadata-simple-modal .arco-modal-footer')
    expect(styleSource).toContain('text-align: right')
    expect(styleSource).toContain('padding: 20px 20px 0')
    expect(styleSource).not.toContain('.metadata-create-row')
    expect(styleSource).not.toContain('.metadata-create-label')
    expect(styleSource).not.toContain('.product-metadata-modal')
    expect(styleSource).not.toContain('width: min(')
    expect(styleSource).not.toContain('font-size: 28px')
    expect(styleSource).not.toContain('height: 64px')
  })
})
