import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

const productDetailSource = readFileSync(
  new URL('../src/views/ProductDetailView.vue', import.meta.url),
  'utf-8',
)

const productSectionCardSource = readFileSync(
  new URL('../src/components/products/ProductSectionCard.vue', import.meta.url),
  'utf-8',
)

const productDetailInfoGridSource = readFileSync(
  new URL('../src/components/products/ProductDetailInfoGrid.vue', import.meta.url),
  'utf-8',
)

const metricSummaryStripSource = readFileSync(
  new URL('../src/components/common/MetricSummaryStrip.vue', import.meta.url),
  'utf-8',
)

const productCatalogSource = readFileSync(
  new URL('../src/data/productCatalog.ts', import.meta.url),
  'utf-8',
)

const getStyleRule = (selector: string) => {
  const match = productDetailSource.match(new RegExp(`\\${selector} \\{[\\s\\S]*?\\n\\}`))
  return match?.[0] ?? ''
}

const getMediaBlock = (mediaQuery: string) => {
  const marker = `@media (${mediaQuery}) {`
  const startIndex = productDetailSource.indexOf(marker)
  if (startIndex === -1) return ''

  let depth = 0
  for (let index = startIndex; index < productDetailSource.length; index += 1) {
    const character = productDetailSource[index]
    if (character === '{') {
      depth += 1
    }
    if (character === '}') {
      depth -= 1
      if (depth === 0) {
        return productDetailSource.slice(startIndex, index + 1)
      }
    }
  }

  return ''
}

const getMediaStyleRule = (mediaQuery: string, selector: string) => {
  const mediaBlock = getMediaBlock(mediaQuery)
  const match = mediaBlock.match(new RegExp(`\\${selector} \\{[\\s\\S]*?\\n  \\}`))
  return match?.[0] ?? ''
}

const getConstArraySource = (name: string) => {
  const markerMatch = productDetailSource.match(new RegExp(`const ${name}(?::[^=]+)? = \\[`))
  const startIndex = markerMatch?.index ?? -1
  if (startIndex === -1) return ''

  const endIndex = productDetailSource.indexOf('\n]\n\nconst', startIndex)
  if (endIndex === -1) return productDetailSource.slice(startIndex)

  return productDetailSource.slice(startIndex, endIndex + 2)
}

const getProductSectionStyleRule = (selector: string) => {
  const match = productSectionCardSource.match(new RegExp(`\\${selector} \\{[\\s\\S]*?\\n\\}`))
  return match?.[0] ?? ''
}

const getInfoGridStyleRule = (selector: string) => {
  const match = productDetailInfoGridSource.match(new RegExp(`\\${selector} \\{[\\s\\S]*?\\n\\}`))
  return match?.[0] ?? ''
}

const getInfoGridStyleRuleContaining = (selector: string) => {
  const unescapedSelector = selector.replace(/\\([()])/g, '$1')
  const rules = productDetailInfoGridSource.match(/(?:^|\n)[^{]+\{[\s\S]*?\n\}/g) ?? []
  return rules.find((rule) => rule.includes(unescapedSelector)) ?? ''
}

const getMetricSummaryStyleRule = (selector: string) => {
  const match = metricSummaryStripSource.match(new RegExp(`\\${selector} \\{[\\s\\S]*?\\n\\}`))
  return match?.[0] ?? ''
}

describe('ProductDetailView overview card source', () => {
  it('labels the edit page as a product detail page', () => {
    expect(productDetailSource).toContain("isCreateMode.value ? '新建商品' : '商品详情'")
    expect(productDetailSource).not.toContain("isCreateMode.value ? '新建商品' : '编辑商品'")
  })

  it('uses the account-style reference layout for the product overview card', () => {
    expect(productDetailSource).toContain('class="overview-profile"')
    expect(productDetailSource).toContain('class="overview-identity"')
    expect(productDetailSource).toContain('class="overview-title-row"')

    expect(productDetailSource).not.toContain('class="overview-stats"')
    expect(productDetailSource).not.toContain('class="overview-stat"')
    expect(productDetailSource).not.toContain('class="overview-right"')
    expect(productDetailSource).not.toContain('class="overview-metric"')
  })

  it('uses SKU as the overview title and product metadata as the description', () => {
    expect(productDetailSource).toContain("<strong>{{ draft.basicInfo.sku || '请先填写 SKU' }}</strong>")
    expect(productDetailSource).toContain('overviewDescriptionParts')
    expect(productDetailSource).toContain('draft.value.basicInfo.chineseName')
    expect(productDetailSource).toContain('draft.value.basicInfo.englishName')
    expect(productDetailSource).toContain('draft.value.basicInfo.russianName')
    expect(productDetailSource).toContain('draft.value.basicInfo.brand')
    expect(productDetailSource).toContain('draft.value.basicInfo.category')
    expect(productDetailSource).toContain('.map((value) => value.trim()).filter(Boolean)')
    expect(productDetailSource).toContain('v-for="(part, index) in overviewDescriptionParts"')
    expect(productDetailSource).toContain('class="overview-description-separator"')
    expect(productDetailSource).not.toContain("<strong>{{ draft.basicInfo.chineseName || '未命名商品' }}</strong>")
    expect(productDetailSource).not.toContain(".join('·')")
  })

  it('keeps two pixels of space around overview description separators', () => {
    const separatorRule = getStyleRule('.overview-description-separator')

    expect(separatorRule).toContain('margin: 0 2px')
  })

  it('uses an eight pixel rounded rectangle for the product preview image', () => {
    const previewRule = getStyleRule('.image-preview')
    const previewImageRule = getStyleRule('.image-preview img')

    expect(previewRule).toContain('border-radius: 8px')
    expect(previewImageRule).toContain('border-radius: 8px')
    expect(previewRule).not.toContain('border-radius: 50%')
  })

  it('removes section description copy from the product detail panels', () => {
    expect(productDetailSource).toContain('<ProductSectionCard title="基础信息">')
    expect(productDetailSource).not.toContain('先建立 SKU 主数据，后续订单、库存和采购都围绕这里的唯一 SKU 展开。')
    expect(productDetailSource).not.toContain('用于后续物流费用估算和发货体积计算。')
    expect(productDetailSource).not.toContain('保留报关基础字段和物流属性标签，为后续履约和清关链路预留结构。')
    expect(productDetailSource).not.toContain('第一版允许手工维护最近采购信息，后续做采购单时再自动回写。')
    expect(productDetailSource).not.toContain('一个内部 SKU 可以绑定多个平台、多个店铺、多个平台商品。')
  })

  it('renders the basic information area as borderless responsive editable field rows', () => {
    const gridRule = getInfoGridStyleRule('.basic-detail-grid')
    const mediumGridRule = productDetailInfoGridSource.match(/@media \(max-width: 1199px\) \{[\s\S]*?\.basic-detail-grid \{[\s\S]*?\n  \}/)?.[0] ?? ''
    const smallGridRule = productDetailInfoGridSource.match(/@media \(max-width: 768px\) \{[\s\S]*?\.basic-detail-grid \{[\s\S]*?\n  \}/)?.[0] ?? ''
    const fieldRule = getInfoGridStyleRule('.basic-detail-field')
    const labelRule = getInfoGridStyleRule('.basic-detail-label')
    const mainRule = getInfoGridStyleRule('.basic-detail-main')
    const displayRule = getInfoGridStyleRule('.basic-detail-display')
    const valueRule = getInfoGridStyleRule('.basic-detail-value')
    const editRule = getInfoGridStyleRule('.basic-detail-edit-button')
    const statusRule = getInfoGridStyleRule('.basic-detail-status')
    const actionsRule = getInfoGridStyleRule('.basic-detail-actions')
    const actionRule = getInfoGridStyleRule('.basic-detail-action')
    const saveActionRule = getInfoGridStyleRule('.basic-detail-action.is-save')
    const cancelActionRule = getInfoGridStyleRule('.basic-detail-action.is-cancel')
    const actionIconRule = getInfoGridStyleRule('.basic-detail-action :deep\\(svg\\)')
    const editorControlRule = getInfoGridStyleRule('.basic-detail-editor-control')
    const scopedEditorControlRule = getInfoGridStyleRuleContaining('.basic-detail-editor :deep\\(.arco-select-view-single\\)')
    const scopedEditorInputRule = getInfoGridStyleRuleContaining('.basic-detail-editor :deep\\(.arco-input-wrapper\\)')
    const scopedEditorNumberRule = getInfoGridStyleRuleContaining('.basic-detail-editor :deep\\(.arco-input-number\\)')

    expect(productDetailInfoGridSource).toContain("export type ProductDetailInfoControl = 'readonly' | 'text' | 'select' | 'combobox' | 'number' | 'dimension' | 'multiselect' | 'tag' | 'date' | 'textarea'")
    expect(productDetailInfoGridSource).toContain('export type ProductDetailInfoItem = {')
    expect(productDetailSource).toContain('const basicDetailItems = computed<BasicDetailItem[]>(() => [')
    expect(productDetailSource).not.toContain('const basicDetailColumns = computed(() => {')
    expect(productDetailSource).not.toContain('const columns: BasicDetailItem[][] = [[], [], []]')
    expect(productDetailSource).not.toContain('columns[index % columns.length].push(item)')
    expect(productDetailSource).toContain("key: 'sku', label: 'SKU', required: true, control: isCreateMode.value ? 'text' : 'readonly'")
    expect(productDetailSource).toContain("key: 'brand', label: '品牌', control: 'text'")
    expect(productDetailSource).toContain("key: 'chineseName', label: '商品中文名', required: true, control: 'text'")
    expect(productDetailSource).toContain("key: 'englishName', label: '商品英文名', control: 'text'")
    expect(productDetailSource).toContain("key: 'russianName', label: '商品俄文名', control: 'text'")
    expect(productDetailSource).toContain("key: 'barcode', label: '条码', control: 'text', mono: true")
    expect(productDetailSource).toContain("key: 'category', label: '类目', control: 'select', options: categoryEditOptions")
    expect(productDetailSource).toContain("key: 'material', label: '材质', control: 'combobox', options: materialOptions")
    expect(productDetailSource).toContain("key: 'specModel', label: '规格型号', control: 'text'")
    expect(productDetailSource).toContain("key: 'status', label: '状态', required: true, control: 'select', options: productStatusOptions")
    expect(productDetailSource).toContain("key: 'grossWeight', label: '毛重 (kg)', control: 'number'")
    expect(productDetailSource).toContain("key: 'netWeight', label: '净重 (kg)', control: 'number'")
    expect(productDetailSource).toContain("key: 'packageSize', label: '包装尺寸 (cm)', control: 'dimension'")

    expect(productDetailInfoGridSource).toContain('const editingKeys = ref<Record<string, true>>({})')
    expect(productDetailInfoGridSource).toContain('const fieldDrafts = ref<Record<string, any>>({})')
    expect(productDetailInfoGridSource).toContain('const dimensionDrafts = ref<Record<string, [number | undefined, number | undefined, number | undefined]>>({})')
    expect(productDetailInfoGridSource).toContain('const isEditing = (key: string) => Boolean(editingKeys.value[key])')
    expect(productDetailInfoGridSource).toContain('editingKeys.value = { ...editingKeys.value, [item.key]: true }')
    expect(productDetailInfoGridSource).toContain('@click="startEdit(item)"')
    expect(productDetailInfoGridSource).toContain('@click="saveEdit(item)"')
    expect(productDetailInfoGridSource).toContain('@click="cancelEdit(item.key)"')
    expect(productDetailInfoGridSource).toContain('v-if="isEditing(item.key)"')
    expect(productDetailInfoGridSource).toContain("'is-editing': isEditing(item.key)")
    expect(productDetailInfoGridSource).toContain('v-model="fieldDrafts[item.key]"')
    expect(productDetailInfoGridSource).toContain('v-model="dimensionDrafts[item.key][0]"')
    expect(productDetailInfoGridSource).not.toContain('editingKey === item.key')
    expect(productDetailInfoGridSource).not.toContain('editingKey.value = item.key')
    expect(productDetailInfoGridSource).toContain('<icon-edit />')
    expect(productDetailInfoGridSource).toContain('<icon-check />')
    expect(productDetailInfoGridSource).toContain('<icon-close />')
    expect(productDetailInfoGridSource).toContain(':aria-label="`保存${item.label}`"')
    expect(productDetailInfoGridSource).toContain('class="basic-detail-action is-cancel"')
    expect(productDetailInfoGridSource).toContain('class="basic-detail-editor-control"')
    expect(productDetailInfoGridSource).toContain('class="basic-detail-main"')
    expect(productDetailInfoGridSource).toContain('v-for="item in items"')
    expect(productDetailSource).not.toContain('v-for="(column, columnIndex) in basicDetailColumns"')
    expect(productDetailSource).not.toContain('class="basic-detail-column"')
    expect(productDetailSource).not.toContain('v-for="item in column"')
    expect(productDetailInfoGridSource).toMatch(/<div v-else class="basic-detail-display">[\s\S]*class="basic-detail-edit-button"[\s\S]*<\/div>/)
    expect(productDetailInfoGridSource).not.toContain('<icon-check />\n                    保存')
    expect(productDetailInfoGridSource).not.toContain('<icon-close />\n                    取消')
    expect(productDetailSource).not.toContain('v-model="draft.basicInfo.chineseName"')
    expect(productDetailInfoGridSource).not.toContain('.basic-detail-field:hover .basic-detail-edit-button')

    expect(gridRule).toContain('grid-template-columns: repeat(3, minmax(0, 1fr))')
    expect(gridRule).toContain('align-items: start')
    expect(gridRule).toContain('row-gap: 14px')
    expect(gridRule).toContain('column-gap: 48px')
    expect(gridRule).toContain('padding-bottom: 20px')
    expect(mediumGridRule).toContain('grid-template-columns: repeat(2, minmax(0, 1fr))')
    expect(mediumGridRule).toContain('column-gap: 32px')
    expect(smallGridRule).toContain('grid-template-columns: 1fr')
    expect(fieldRule).toContain('display: grid')
    expect(fieldRule).toContain('grid-template-columns: 96px minmax(0, 1fr)')
    expect(fieldRule).toContain('align-items: center')
    expect(fieldRule).toContain('min-height: 32px')
    expect(fieldRule).toContain('border: 0')
    expect(fieldRule).toContain('background: transparent')
    expect(fieldRule).not.toContain('padding:')
    expect(fieldRule).not.toContain('padding: 4px 0')
    expect(fieldRule).not.toContain('border: 1px solid var(--product-color-border)')
    expect(labelRule).toContain('color: var(--product-color-text-tertiary)')
    expect(labelRule).toContain('font-size: 13px')
    expect(mainRule).toContain('min-width: 0')
    expect(displayRule).toContain('min-height: 32px')
    expect(displayRule).toContain('gap: 4px')
    expect(valueRule).toContain('font-size: 13px')
    expect(statusRule).toContain('font-size: 13px')
    expect(statusRule).toContain('padding: 1px 10px')
    expect(editRule).toContain('width: 14px')
    expect(editRule).toContain('height: 14px')
    expect(editRule).toContain('border: 0')
    expect(editRule).toContain('opacity: 1')
    expect(actionRule).toContain('width: 24px')
    expect(actionRule).toContain('height: 24px')
    expect(actionRule).toContain('padding: 0')
    expect(actionRule).toContain('border: 0')
    expect(actionRule).toContain('background: transparent')
    expect(actionRule).not.toContain('height: 26px')
    expect(actionRule).not.toContain('padding: 0 8px')
    expect(actionRule).not.toContain('border: 1px solid var(--product-color-border)')
    expect(actionRule).not.toContain('width: 14px')
    expect(actionRule).not.toContain('height: 14px')
    expect(actionsRule).toContain('gap: 4px')
    expect(actionsRule).not.toContain('gap: 16px')
    expect(saveActionRule).toContain('color: #00b42a')
    expect(cancelActionRule).toContain('color: #f53f3f')
    expect(actionIconRule).toContain('width: 14px')
    expect(actionIconRule).toContain('height: 14px')
    expect(editorControlRule).toContain('height: 28px')
    expect(editorControlRule).toContain('min-height: 28px')
    expect(scopedEditorControlRule).toContain('height: 28px')
    expect(scopedEditorControlRule).toContain('min-height: 28px')
    expect(scopedEditorControlRule).toContain('line-height: 28px')
    expect(scopedEditorInputRule).toContain('height: 28px')
    expect(scopedEditorInputRule).toContain('min-height: 28px')
    expect(scopedEditorNumberRule).toContain('height: 28px')
    expect(scopedEditorNumberRule).toContain('min-height: 28px')
  })

  it('extracts the detail field matrix into a reusable component for lower sections', () => {
    expect(productDetailSource).toContain("import ProductDetailInfoGrid, { type ProductDetailInfoItem, type ProductDetailInfoValue } from '../components/products/ProductDetailInfoGrid.vue'")
    expect(productDetailSource).toContain("import ConfigurableDataTable from '../components/common/ConfigurableDataTable.vue'")
    expect(productDetailSource).toMatch(/<ProductSectionCard title="基础信息">[\s\S]*<ProductDetailInfoGrid[\s\S]*:items="basicDetailItems"[\s\S]*@save="saveDetailInfoField"/)
    expect(productDetailSource).toMatch(/<ProductSectionCard title="报关和物流属性">[\s\S]*<ProductDetailInfoGrid[\s\S]*:items="logisticsInfoItems"[\s\S]*@save="saveDetailInfoField"/)
    expect(productDetailSource).toMatch(/<ProductSectionCard title="采购参考">[\s\S]*<ProductDetailInfoGrid[\s\S]*:items="procurementInfoItems"[\s\S]*@save="saveDetailInfoField"/)
    expect(productDetailSource).toContain('const logisticsInfoItems = computed<ProductDetailInfoItem[]>(() => [')
    expect(productDetailSource).toContain('const procurementInfoItems = computed<ProductDetailInfoItem[]>(() => [')
    expect(productDetailSource).toContain("key: 'logistics.customsChineseName'")
    expect(productDetailSource).toContain("key: 'procurement.defaultPurchaseUrl'")
    expect(productDetailSource).not.toContain("key: 'logistics.sensitiveTags'")
    expect(productDetailSource).not.toContain("label: '敏感货标签'")
    expect(productDetailSource).not.toContain('formatStringListValue(draft.value.logistics.sensitiveTags)')
    expect(productDetailSource).toContain('const saveDetailInfoField = (key: string, value: ProductDetailInfoValue) => {')
    expect(productDetailSource).not.toMatch(/<ProductSectionCard title="报关和物流属性">[\s\S]*<a-form/)
    expect(productDetailSource).not.toMatch(/<ProductSectionCard title="采购参考">[\s\S]*<a-form/)
  })

  it('supports create-mode SKU entry, blank default statuses, and an overview submit button', () => {
    expect(productCatalogSource).toContain("export type ProductStatus = '' | 'normal' | 'disabled' | 'draft'")
    expect(productCatalogSource).toContain("status: ''")
    expect(productDetailSource).toContain("'': '-'")
    expect(productDetailSource).toContain("'': undefined")
    expect(productDetailSource).toContain("key: 'sku', label: 'SKU', required: true, control: isCreateMode.value ? 'text' : 'readonly'")
    expect(productDetailSource).toContain("case 'sku':")
    expect(productDetailSource).toContain("draft.value.basicInfo.sku = value")
    expect(productDetailSource).not.toContain("if (key === 'sku') return")
    expect(productDetailSource).toContain('<a-tag v-if="draft.basicInfo.status" :color="statusToneMap[draft.basicInfo.status]">{{ statusLabelMap[draft.basicInfo.status] }}</a-tag>')
    expect(productDetailSource).toMatch(/key: 'status'[\s\S]*value: statusLabelMap\[draft.value.basicInfo.status\][\s\S]*editValue: draft.value.basicInfo.status[\s\S]*statusTone: statusToneMap\[draft.value.basicInfo.status\]/)
    expect(productDetailSource).toMatch(/key: 'procurement.status'[\s\S]*value: formatOptionValue\(draft.value.procurement.status, procurementStatusOptions\)[\s\S]*statusTone: procurementStatusToneMap\[draft.value.procurement.status\]/)
    expect(productDetailSource).toContain('const submitProduct = () => {')
    expect(productDetailSource).toContain("catalogStore.saveProduct({ mode: 'create', product: draft.value })")
    expect(productDetailSource).toMatch(/<section class="overview-card">[\s\S]*<div v-if="isCreateMode" class="overview-actions">[\s\S]*<a-button type="primary" @click="submitProduct">提交商品<\/a-button>/)
    expect(productDetailSource).toContain('class="overview-actions"')
    expect(getStyleRule('.overview-actions')).toContain('margin-left: auto')
    expect(productDetailSource).not.toContain('class="product-submit-bar"')
    expect(productDetailSource).not.toContain('.product-submit-bar')
  })

  it('places procurement URL before notes on its own row and displays procurement status as a badge', () => {
    expect(productDetailSource).toContain("const procurementStatusToneMap: Record<ProductRecord['procurement']['status'], 'green' | 'orange' | 'red' | undefined> = {")
    expect(productDetailSource).toContain("'': undefined")
    expect(productDetailSource).toContain("'temporary-out-of-stock': 'orange'")
    expect(productDetailSource).toContain("stopped: 'red'")
    expect(productDetailSource).toContain("risk: 'red'")
    expect(productDetailSource).toMatch(/key: 'procurement.status'[\s\S]*statusTone: procurementStatusToneMap\[draft.value.procurement.status\]/)
    expect(productDetailSource).toMatch(/key: 'procurement.status'[\s\S]*key: 'procurement.defaultPurchaseUrl'[\s\S]*href: draft.value.procurement.defaultPurchaseUrl.trim\(\) \|\| undefined[\s\S]*span: 'wide'[\s\S]*key: 'procurement.note'/)
    expect(productDetailSource).not.toMatch(/key: 'procurement.defaultPurchaseUrl'[\s\S]*key: 'procurement.purchasable'/)
    expect(productDetailInfoGridSource).toContain('href?: string')
    expect(productDetailInfoGridSource).toContain('v-else-if="item.href && item.value !== \'-\'"')
    expect(productDetailInfoGridSource).toContain('class="basic-detail-link"')
    expect(productDetailInfoGridSource).toContain(':href="item.href"')
    expect(productDetailInfoGridSource).toContain('target="_blank"')
    expect(productDetailInfoGridSource).toContain('rel="noopener noreferrer"')

    const linkRule = getInfoGridStyleRule('.basic-detail-link')
    expect(linkRule).toContain('color: var(--product-color-primary)')
    expect(linkRule).toContain('font-size: 13px')
    expect(linkRule).toContain('overflow-wrap: anywhere')
  })

  it('uses the batch inventory table treatment for platform store mappings', () => {
    expect(productDetailSource).toContain("import type { ConfigurableTableColumn } from '../data/configurableTable'")
    expect(productDetailSource).toContain("type MappingColumnKey = 'platform' | 'store' | 'platformProductId' | 'platformSkuId' | 'platformBarcode' | 'listingStatus' | 'linkedAt'")
    expect(productDetailSource).toContain('type MappingTableColumnData = ConfigurableTableColumn<MappingColumnKey> & { title: string }')
    expect(productDetailSource).toContain('const mappingVisibleColumnKeys: MappingColumnKey[] = [')
    expect(productDetailSource).toContain("'platformBarcode'")
    expect(productDetailSource).toContain("'linkedAt'")
    expect(productDetailSource).toContain("{ settingsKey: 'platform', title: '平台'")
    expect(productDetailSource).toContain("{ settingsKey: 'store', title: '店铺'")
    expect(productDetailSource).toContain("{ settingsKey: 'platformProductId', title: '平台商品 ID'")
    expect(productDetailSource).toContain("{ settingsKey: 'platformSkuId', title: '平台 SKU'")
    expect(productDetailSource).toContain("{ settingsKey: 'platformBarcode', title: '平台条码'")
    expect(productDetailSource).toContain("{ settingsKey: 'listingStatus', title: '状态'")
    expect(productDetailSource).toContain("{ settingsKey: 'linkedAt', title: '关联时间'")
    expect(productDetailSource).toContain("{ title: '操作', slotName: 'operation'")
    expect(productDetailSource).not.toContain("title: '店铺 SKU'")
    expect(productDetailSource).not.toContain("title: '平台商品链接'")
    expect(productDetailSource).not.toContain("title: '平台上架状态'")

    expect(productDetailSource).toContain('<a-button type="primary" size="small" @click="addMapping">')
    expect(productDetailSource).toContain('<ConfigurableDataTable')
    expect(productDetailSource).toContain(':columns="mappingColumns"')
    expect(productDetailSource).toContain(':default-visible-keys="mappingVisibleColumnKeys"')
    expect(productDetailSource).toContain('table-class="data-table"')
    expect(productDetailSource).toContain('wrapper-class="mapping-table"')
    expect(productDetailSource).toContain('<template #platform="{ record }">')
    expect(productDetailSource).toContain('class="mapping-platform-badge"')
    expect(productDetailSource).toContain('getPlatformShortLabel((record as ProductPlatformMapping).platform)')
    expect(productDetailSource).toContain('<template #listingStatus="{ record }">')
    expect(productDetailSource).toContain('class="mapping-status"')
    expect(productDetailSource).toContain('getMappingStatusLabel((record as ProductPlatformMapping).listingStatus)')
    expect(productDetailSource).toContain('<template #operation="{ record }">')
    expect(productDetailSource).toContain('class="mapping-edit-link"')
    expect(productDetailSource).toContain('class="mapping-delete-link"')
    expect(productDetailSource).toContain('class="mapping-row-action is-save"')
    expect(productDetailSource).toContain('class="mapping-row-action is-cancel"')
    expect(productDetailSource).toMatch(/class="mapping-row-action is-save"[\s\S]*>\s*保存\s*<\/button>/)
    expect(productDetailSource).toMatch(/class="mapping-row-action is-cancel"[\s\S]*>\s*取消\s*<\/button>/)
    expect(productDetailSource).not.toMatch(/class="mapping-row-action is-save"[\s\S]*<icon-check \/>/)
    expect(productDetailSource).not.toMatch(/class="mapping-row-action is-cancel"[\s\S]*<icon-close \/>/)
    expect(productDetailSource).toContain('编辑')
    expect(productDetailSource).toContain('删除')
    expect(productDetailSource).toContain('const removeMapping = (mappingId: string) => {')
    expect(productDetailSource).not.toContain('<template #storeSku="{ record }">')
    expect(productDetailSource).not.toContain('<template #productUrl="{ record }">')

    expect(productCatalogSource).toContain('platformBarcode: string')
    expect(productCatalogSource).toContain('linkedAt: string')
    expect(productCatalogSource).toContain("platformBarcode: ''")
    expect(productCatalogSource).toContain("linkedAt: ''")

    const mappingTableRule = getStyleRule('.mapping-table')
    const mappingBadgeRule = getStyleRule('.mapping-platform-badge')
    const mappingStatusRule = getStyleRule('.mapping-status')
    const mappingEditLinkRule = getStyleRule('.mapping-edit-link')
    const mappingDeleteLinkRule = getStyleRule('.mapping-delete-link')
    const mappingOperationRule = getStyleRule('.mapping-operation-links')

    expect(mappingTableRule).toContain('--workspace-color-primary: var(--product-color-primary)')
    expect(mappingTableRule).toContain('--workspace-color-border: var(--product-color-border)')
    expect(mappingBadgeRule).toContain('display: inline-flex')
    expect(mappingBadgeRule).toContain('border-radius: 4px')
    expect(mappingStatusRule).toContain('display: inline-flex')
    expect(mappingStatusRule).toContain('gap: 8px')
    expect(mappingEditLinkRule).toContain('color: var(--product-color-primary)')
    expect(mappingEditLinkRule).toContain('border: 0')
    expect(mappingDeleteLinkRule).toContain('color: #f53f3f')
    expect(mappingDeleteLinkRule).toContain('border: 0')
    expect(mappingOperationRule).toContain('display: inline-flex')
    expect(mappingOperationRule).toContain('gap: 12px')
  })

  it('adds a media information photo wall between basic and logistics sections', () => {
    const mediaListRule = getStyleRule('.media-info-list')
    const mediaRowRule = getStyleRule('.media-info-row')
    const mediaLabelRule = getStyleRule('.media-info-label')
    const mediaWallRule = getStyleRule('.media-info-wall')
    const mediaUploadRule = getStyleRule('.media-picture-upload')
    const mediaUploadListRule = getStyleRule('.media-picture-upload :deep\\(.arco-upload-list-type-picture-card\\)')
    const mediaUploadPictureRule = getStyleRule('.media-picture-upload :deep\\(.arco-upload-list-picture\\)')
    const mediaUploadCardRule = getStyleRule('.media-picture-upload :deep\\(.arco-upload-picture-card\\)')
    const mediaUploadImageRule = getStyleRule('.media-picture-upload :deep\\(.arco-upload-list-picture img\\)')
    const mediaUploadTipRule = getStyleRule('.media-picture-upload :deep\\(.arco-upload-tip\\)')
    const videoUploadPictureRule = getStyleRule('.media-picture-upload.is-video :deep\\(.arco-upload-list-picture\\)')
    const videoDefaultPlayRule = getStyleRule('.media-picture-upload.is-video :deep\\(.arco-upload-list-picture::after\\)')
    const videoHoverPlayRule = getStyleRule('.media-picture-upload.is-video :deep\\(.arco-upload-list-picture:hover::after\\)')
    const videoUploadMaskRule = getStyleRule('.media-picture-upload.is-video :deep\\(.arco-upload-list-picture-mask\\)')
    const videoPreviewRule = getStyleRule('.media-video-preview')

    expect(productDetailSource).toMatch(/<ProductSectionCard title="基础信息">[\s\S]*<ProductSectionCard title="图文信息">[\s\S]*<ProductSectionCard title="报关和物流属性">/)
    expect(productDetailSource).toContain("type MediaUploadKind = 'image' | 'video'")
    expect(productDetailSource).toContain('type MediaFileItem = FileItem & {')
    expect(productDetailSource).toContain('const mediaInfoRows = computed<MediaInfoRow[]>(() => {')
    expect(productDetailSource).toContain('draft.value.basicInfo.mainImage')
    expect(productDetailSource).toContain('draft.value.basicInfo.galleryImages.filter(Boolean)')
    expect(productDetailSource).toContain('const overviewMainImage = computed(() => {')
    expect(productDetailSource).toContain("const uploadedMainImage = mediaUploadFiles.value['main-image']?.[0]")
    expect(productDetailSource).toContain('return uploadedMainImage?.sourceUrl || uploadedMainImage?.url || draft.value.basicInfo.mainImage')
    expect(productDetailSource).toContain('<img v-if="overviewMainImage" :src="overviewMainImage" :alt="draft.basicInfo.chineseName || draft.basicInfo.sku" />')
    expect(productDetailSource).toContain("label: '商品主图'")
    expect(productDetailSource).toContain("label: '主图视频'")
    expect(productDetailSource).toContain("label: '详情页图片'")
    expect(productDetailSource).toContain("label: '包装图'")
    expect(productDetailSource).toContain("createMediaUploadAction('upload-main-image', '上传主图')")
    expect(productDetailSource).not.toContain("createMediaUploadAction('upload-transparent-image', '上传透明图')")
    expect(productDetailSource).not.toContain('上传透明图')
    expect(productDetailSource).toContain("createMediaUploadAction('upload-main-video', '上传视频', 'video')")
    expect(productDetailSource).toContain("createMediaUploadAction('upload-detail-image', '上传图片')")
    expect(productDetailSource).toContain("createMediaUploadAction('upload-package-image', '上传包装图')")
    expect(productDetailSource).toContain('const mediaUploadFiles = ref<Record<string, MediaFileItem[]>>({})')
    expect(productDetailSource).toContain('const getMediaFileList = (key: string, fallbackFileList: MediaFileItem[]) => mediaUploadFiles.value[key] ?? fallbackFileList')
    expect(productDetailSource).toContain('const createVideoCoverFromFile = (file: File) => new Promise<string>((resolve, reject) => {')
    expect(productDetailSource).toContain("document.createElement('video')")
    expect(productDetailSource).toContain("canvas.toDataURL('image/jpeg', 0.82)")
    expect(productDetailSource).toContain("file.type.startsWith('video/')")
    expect(productDetailSource).toContain('const mediaPreviewObjectUrls = ref<Record<string, string>>({})')
    expect(productDetailSource).toContain('const createMediaPreviewFileItem = (key: string, item: FileItem): MediaFileItem => {')
    expect(productDetailSource).toContain('URL.createObjectURL(file)')
    expect(productDetailSource).toContain('const openVideoPreview = (fileItem: FileItem) => {')
    expect(productDetailSource).toContain('videoPreviewVisible.value = true')
    expect(productDetailSource).toContain('videoPreviewSrc.value = src')
    expect(productDetailSource).toContain('const handleMediaPreview = (kind: MediaUploadKind, fileItem: FileItem) => {')
    expect(productDetailSource).toContain('const handleMediaUploadChange = (key: string, kind: MediaUploadKind, fileList: FileItem[], fileItem: FileItem) => {')
    expect(productDetailSource).toContain('void updateVideoCover(key, fileItem)')
    expect(productDetailSource).toContain('v-for="row in mediaInfoRows"')
    expect(productDetailSource).toContain('<a-upload')
    expect(productDetailSource).toContain('list-type="picture-card"')
    expect(productDetailSource).toContain(':file-list="row.fileList"')
    expect(productDetailSource).toContain('@change="(fileList, fileItem) => handleMediaUploadChange(row.key, row.uploadActions[0].kind, fileList, fileItem)"')
    expect(productDetailSource).toContain('image-preview')
    expect(productDetailSource).toContain('class="media-picture-upload"')
    expect(productDetailSource).toContain(':class="{ \'is-video\': row.uploadActions[0].kind === \'video\' }"')
    expect(productDetailSource).toContain(':show-remove-button="true"')
    expect(productDetailSource).toContain(':image-preview="row.uploadActions[0].kind !== \'video\'"')
    expect(productDetailSource).toContain('@preview="(fileItem) => handleMediaPreview(row.uploadActions[0].kind, fileItem)"')
    expect(productDetailSource).toContain(':tip="row.uploadActions[0].label"')
    expect(productDetailSource).toContain(':tip="action.label"')
    expect(productDetailSource).toContain("v-for=\"action in row.uploadActions.slice(1)\"")
    expect(productDetailSource).toContain(':show-file-list="false"')
    expect(productDetailSource).not.toContain(':show-remove-button="false"')
    expect(productDetailSource).not.toContain('class="media-info-required"')
    expect(productDetailSource).not.toContain('.media-info-required')
    expect(productDetailSource).not.toContain('<span v-if="row.required"')
    expect(productDetailSource).not.toContain('影响商品曝光引流效果')
    expect(productDetailSource).not.toContain('class="media-info-hint"')
    expect(productDetailSource).not.toContain('.media-info-hint')
    expect(productDetailSource).not.toContain('#preview-icon')
    expect(productDetailSource).not.toContain('class="media-video-play-button"')
    expect(productDetailSource).not.toContain('<icon-play-circle-fill />')
    expect(productDetailSource).toContain('<a-modal')
    expect(productDetailSource).toContain('v-model:visible="videoPreviewVisible"')
    expect(productDetailSource).toContain('<video')
    expect(productDetailSource).toContain(':src="videoPreviewSrc"')
    expect(productDetailSource).toContain('controls')
    expect(productDetailSource).not.toContain('class="media-asset-tile"')
    expect(productDetailSource).not.toContain("'media-upload-tile': !item.src")
    expect(productDetailSource).not.toContain('<template #upload-button>')
    expect(productDetailSource).not.toContain('class="media-upload-button"')
    expect(productDetailSource).not.toContain('IconImage')

    expect(mediaListRule).toContain('display: flex')
    expect(mediaListRule).toContain('flex-direction: column')
    expect(mediaListRule).toContain('padding-bottom: 20px')
    expect(mediaRowRule).toContain('display: grid')
    expect(mediaRowRule).toContain('grid-template-columns: 96px minmax(0, 1fr)')
    expect(mediaRowRule).toContain('gap: 12px')
    expect(mediaLabelRule).toContain('color: var(--product-color-text-tertiary)')
    expect(mediaLabelRule).toContain('font-size: 13px')
    expect(mediaLabelRule).toContain('font-weight: 500')
    expect(mediaLabelRule).toContain('line-height: 22px')
    expect(mediaLabelRule).not.toContain('border-bottom')
    expect(mediaWallRule).toContain('display: flex')
    expect(mediaWallRule).toContain('flex-wrap: wrap')
    expect(mediaUploadRule).toContain('display: flex')
    expect(mediaUploadRule).toContain('flex-wrap: wrap')
    expect(mediaUploadRule).toContain('gap: 16px')
    expect(mediaUploadListRule).toContain('display: flex')
    expect(mediaUploadListRule).toContain('gap: 16px')
    expect(mediaUploadPictureRule).toContain('width: 100px')
    expect(mediaUploadPictureRule).toContain('height: 100px')
    expect(mediaUploadCardRule).toContain('width: 100px')
    expect(mediaUploadCardRule).toContain('min-width: 100px')
    expect(mediaUploadCardRule).toContain('height: 100px')
    expect(mediaUploadImageRule).toContain('width: 100px')
    expect(mediaUploadImageRule).toContain('height: 100px')
    expect(mediaUploadTipRule).toContain('font-size: 13px')
    expect(mediaUploadTipRule).toContain('line-height: 22px')
    expect(videoUploadPictureRule).toContain('position: relative')
    expect(videoDefaultPlayRule).toContain("content: ''")
    expect(videoDefaultPlayRule).toContain('width: 36px')
    expect(videoDefaultPlayRule).toContain('height: 36px')
    expect(videoDefaultPlayRule).toContain('background-image')
    expect(videoDefaultPlayRule).toContain('pointer-events: none')
    expect(videoHoverPlayRule).toContain('opacity: 0')
    expect(videoUploadMaskRule).not.toContain('opacity: 1')
    expect(videoUploadMaskRule).not.toContain('background: transparent')
    expect(videoPreviewRule).toContain('width: 100%')
    expect(videoPreviewRule).toContain('max-height: 70vh')
    expect(productDetailSource).not.toContain('.media-upload-button')
  })

  it('uses the requested edit controls for select, combobox, number, and package dimensions', () => {
    expect(productDetailInfoGridSource).toContain('v-if="item.control === \'text\'"')
    expect(productDetailInfoGridSource).toContain('v-else-if="item.control === \'select\'"')
    expect(productDetailInfoGridSource).toContain('v-else-if="item.control === \'combobox\'"')
    expect(productDetailInfoGridSource).toContain('v-else-if="item.control === \'number\'"')
    expect(productDetailInfoGridSource).toContain('v-else-if="item.control === \'dimension\'"')
    expect(productDetailInfoGridSource).toContain(':step="0.001"')
    expect(productDetailInfoGridSource).toContain('class="dimension-editor"')
    expect(productDetailInfoGridSource).toContain('allow-search')
    expect(productDetailInfoGridSource).toContain('allow-create')
    expect(productDetailSource).toContain('options: materialOptions')
    expect(productDetailSource).toContain("{ label: '数码配件', value: '数码配件' }")
    expect(productDetailSource).toContain("{ label: '车载配件', value: '车载配件' }")
    expect(productDetailSource).toContain("{ label: '家居日用', value: '家居日用' }")

    const materialOptionsMatch = productDetailSource.match(/const materialOptions = \[([\s\S]*?)\]/)
    const materialOptionCount = materialOptionsMatch?.[1].match(/label:/g)?.length ?? 0
    expect(materialOptionCount).toBe(17)
  })

  it('maps product status to sale labels and green orange red badges', () => {
    expect(productCatalogSource).toContain("export type ProductStatus = '' | 'normal' | 'disabled' | 'draft'")
    expect(productCatalogSource).toContain("{ label: '在售', value: 'normal' }")
    expect(productCatalogSource).toContain("{ label: '停售', value: 'disabled' }")
    expect(productCatalogSource).toContain("{ label: '草稿', value: 'draft' }")

    expect(productDetailSource).toContain("const statusLabelMap: Record<ProductStatus, string> = {")
    expect(productDetailSource).toContain("'': '-'")
    expect(productDetailSource).toContain("normal: '在售'")
    expect(productDetailSource).toContain("disabled: '停售'")
    expect(productDetailSource).toContain("draft: '草稿'")
    expect(productDetailSource).toContain("const statusToneMap: Record<ProductStatus, 'green' | 'orange' | 'red' | undefined> = {")
    expect(productDetailSource).toContain("'': undefined")
    expect(productDetailSource).toContain("normal: 'green'")
    expect(productDetailSource).toContain("disabled: 'orange'")
    expect(productDetailSource).toContain("draft: 'red'")
    expect(productDetailSource).toContain('statusTone: statusToneMap[draft.value.basicInfo.status]')
    expect(productDetailInfoGridSource).toContain(':class="`is-${item.statusTone}`"')
    expect(productDetailInfoGridSource).toContain('.basic-detail-status.is-green')
    expect(productDetailInfoGridSource).toContain('.basic-detail-status.is-orange')
    expect(productDetailInfoGridSource).toContain('.basic-detail-status.is-red')
  })

  it('adds the product detail tab switcher above the mapping tip', () => {
    expect(productDetailSource).not.toContain('const detailTabs = [')
    expect(productDetailSource).toContain("{ key: 'basic', label: '基础信息' }")
    expect(productDetailSource).toContain("{ key: 'inventory', label: '库存概况' }")
    expect(productDetailSource).toContain("const detailTabs = computed<DetailTab[]>(() => [")
    expect(productDetailSource).toContain("{ key: 'orders', label: '近期订单', count: isCreateMode.value ? undefined : 32 }")
    expect(productDetailSource).toContain("{ key: 'profit', label: '利润概览' }")
    expect(productDetailSource).toContain("{ key: 'reviews', label: '商品评价' }")
    expect(productDetailSource).toContain("{ key: 'changes', label: '变更记录' }")
    expect(productDetailSource).toMatch(/<nav class="product-detail-tabs"[\s\S]*<a-alert class="mapping-tip"/)
    expect(productDetailSource).toContain('class="product-detail-tab-count"')
  })

  it('builds quick Arco-styled content panels for non-basic product detail tabs', () => {
    expect(productDetailSource).toContain("import { Message } from '@arco-design/web-vue'")
    expect(productDetailSource).toContain("import MetricSummaryStrip from '../components/common/MetricSummaryStrip.vue'")
    expect(productDetailSource).toMatch(/const inventorySummaryCards(?::[^=]+)? = \[/)
    expect(productDetailSource).toContain("const inventoryStoreGroups = [")
    expect(productDetailSource).toMatch(/const recentOrderSummaryCards(?::[^=]+)? = \[/)
    expect(productDetailSource).toMatch(/const recentOrderColumns(?::[^=]+)? = \[/)
    expect(productDetailSource).toMatch(/const recentOrderRows(?::[^=]+)? = \[/)
    expect(productDetailSource).toMatch(/const profitSummaryCards(?::[^=]+)? = \[/)
    expect(productDetailSource).toContain('const profitRows: ProfitRow[] = [')
    expect(productDetailSource).toContain("type ReviewColumnKey = 'rating' | 'platform' | 'store' | 'category' | 'content' | 'publishedAt'")
    expect(productDetailSource).toContain('const reviewVisibleColumnKeys: ReviewColumnKey[] = [')
    expect(productDetailSource).toMatch(/const reviewColumns(?::[^=]+)? = \[/)
    expect(productDetailSource).toMatch(/const reviewPlatformOptions(?::[^=]+)? = \[/)
    expect(productDetailSource).toMatch(/const reviewCategoryOptions(?::[^=]+)? = \[/)
    expect(productDetailSource).toMatch(/const reviewRows(?::[^=]+)? = \[/)
    expect(productDetailSource).toMatch(/const changeLogItems(?::[^=]+)? = \[/)

    expect(productDetailSource).toContain('<template v-if="activeDetailTab === \'basic\'">')
    expect(productDetailSource).toContain('<div v-else-if="activeDetailTab === \'inventory\'" class="product-tab-panel">')
    expect(productDetailSource).toContain('<div v-else-if="activeDetailTab === \'orders\'" class="product-tab-panel">')
    expect(productDetailSource).toContain('<div v-else-if="activeDetailTab === \'profit\'" class="product-tab-panel">')
    expect(productDetailSource).toContain('<div v-else-if="activeDetailTab === \'reviews\'" class="product-tab-panel">')
    expect(productDetailSource).toContain('<div v-else-if="activeDetailTab === \'changes\'" class="product-tab-panel">')

    expect(productDetailSource).toContain('<ConfigurableDataTable')
    expect(productDetailSource).toContain(':columns="recentOrderColumns"')
    expect(productDetailSource).toContain(':data="recentOrderRows"')
    expect(productDetailSource).toContain(':columns="reviewColumns"')
    expect(productDetailSource).toContain(':data="filteredReviewRows"')
    expect(productDetailSource).toContain('<QueryFilterPanel class="review-filter-panel">')
    expect(productDetailSource).toContain('wrapper-class="product-tab-data-table review-table"')
    expect(productDetailSource).toContain('<a-rate :model-value="(record as ProductReviewRow).rating" readonly />')
    expect(productDetailSource).toContain(':columns="changeLogColumns"')
    expect(productDetailSource).toContain(':data="changeLogItems"')
    expect(productDetailSource).not.toContain('<a-timeline>')

    const panelRule = getStyleRule('.product-tab-panel')
    const cardRule = getStyleRule('.product-tab-section-card')
    const inventoryStoreCardRule = getStyleRule('.inventory-store-card')
    const sectionHeaderRule = getStyleRule('.product-tab-section-card :deep\\(.arco-card-header\\)')
    const sectionBodyRule = getStyleRule('.product-tab-section-card :deep\\(.arco-card-body\\)')
    const tableRule = getStyleRule('.product-tab-data-table')

    expect(panelRule).toContain('padding-top: 24px')
    expect(panelRule).toContain('display: flex')
    expect(cardRule).toContain('border: 0')
    expect(cardRule).toContain('border-radius: 0')
    expect(cardRule).toContain('background: transparent')
    expect(cardRule).toContain('box-shadow: none')
    expect(cardRule).not.toContain('background: var(--product-color-bg)')
    expect(inventoryStoreCardRule).toContain('margin-top: 8px')
    expect(inventoryStoreCardRule).toContain('margin-bottom: 8px')
    expect(sectionHeaderRule).toContain('padding: 24px 0 8px')
    expect(sectionHeaderRule).toContain('border-bottom: 0')
    expect(sectionBodyRule).toContain('padding: 14px 0 0')
    expect(tableRule).toContain('--workspace-color-bg: var(--color-bg-2)')
    expect(tableRule).toContain('--workspace-color-fill: var(--color-fill-1)')
    expect(tableRule).toContain('--workspace-radius: var(--border-radius-medium)')
    expect(productDetailSource).not.toContain('.product-tab-table :deep(.arco-table-th)')
    expect(productDetailSource).not.toContain('.product-tab-table :deep(.arco-table-td)')
  })

  it('renders product reviews as a filtered table-like detail page', () => {
    const reviewRowsSource = getConstArraySource('reviewRows')
    const reviewCardBodyRule = getStyleRule('.review-detail-card :deep\\(.arco-card-body\\)')
    const filterPanelRule = getStyleRule('.review-filter-panel')
    const dateQuickRule = getStyleRule('.review-date-quick')
    const dateQuickButtonRule = getStyleRule('.review-date-quick button')
    const activeDateQuickButtonRule = getStyleRule('.review-date-quick button.is-active')
    const dateRangeRule = getStyleRule('.review-date-range')
    const filterSearchRule = getStyleRule('.review-keyword-search')
    const tableRule = getStyleRule('.review-table')
    const ratingCellRule = getStyleRule('.review-rating-cell')
    const contentCellRule = getStyleRule('.review-content-cell')
    const timeCellRule = getStyleRule('.review-time-cell')

    expect(productDetailSource).toContain("import QueryActionBar from '../components/common/QueryActionBar.vue'")
    expect(productDetailSource).toContain("import QueryFilterItem from '../components/common/QueryFilterItem.vue'")
    expect(productDetailSource).toContain("import QueryFilterPanel from '../components/common/QueryFilterPanel.vue'")
    expect(productDetailSource).toContain("const reviewDateQuickOptions = [")
    expect(productDetailSource).toContain("{ label: '今天', value: 'today' }")
    expect(productDetailSource).toContain("{ label: '昨天', value: 'yesterday' }")
    expect(productDetailSource).toContain("{ label: '近一个月', value: 'near-month' }")
    expect(productDetailSource).toContain("const reviewPlatformFilter = ref('')")
    expect(productDetailSource).toContain("const reviewStoreFilter = ref('')")
    expect(productDetailSource).toContain("const reviewCategoryFilter = ref('')")
    expect(productDetailSource).toContain("const activeReviewDateQuick = ref('')")
    expect(productDetailSource).toContain('dateQuick: \'\'')
    expect(productDetailSource).toContain('dateRange: []')
    expect(productDetailSource).toContain('const reviewDateRange = ref<string[]>([])')
    expect(productDetailSource).toContain('const reviewSearchKeyword = ref(\'\')')
    expect(productDetailSource).toContain('type ReviewFilterState = {')
    expect(productDetailSource).toContain('const createDefaultReviewFilters = (): ReviewFilterState => ({')
    expect(productDetailSource).toContain('const appliedReviewFilters = ref<ReviewFilterState>(createDefaultReviewFilters())')
    expect(productDetailSource).toContain('const filteredReviewRows = computed(() => {')
    expect(productDetailSource).toContain('const filters = appliedReviewFilters.value')
    expect(productDetailSource).toContain('const applyReviewFilters = () => {')
    expect(productDetailSource).toContain('const getReviewDateRangeByQuick = (dateQuick: string) => {')
    expect(productDetailSource).toContain('const setReviewDateQuick = (dateQuick: string) => {')
    expect(productDetailSource).toContain('reviewDateRange.value = getReviewDateRangeByQuick(dateQuick)')
    expect(productDetailSource).toContain('const handleReviewDateRangeChange = (_value: unknown, _date: unknown, dateString?: Array<string | undefined>) => {')
    expect(productDetailSource).toContain("type ProductReviewRow = {")
    expect(productDetailSource).toContain("type ReviewColumnKey = 'rating' | 'platform' | 'store' | 'category' | 'content' | 'publishedAt'")
    expect(productDetailSource).toContain("type ReviewTableColumnData = ConfigurableTableColumn<ReviewColumnKey> & { title: string }")
    expect(productDetailSource).toContain('const reviewVisibleColumnKeys: ReviewColumnKey[] = [')
    expect(productDetailSource).toContain('const reviewColumns: ReviewTableColumnData[] = [')
    expect(productDetailSource).toContain("{ settingsKey: 'rating', title: '评级', dataIndex: 'rating', slotName: 'rating'")
    expect(productDetailSource).toContain("{ settingsKey: 'platform', title: '平台', dataIndex: 'platform', slotName: 'platform'")
    expect(productDetailSource).toContain("{ settingsKey: 'store', title: '店铺', dataIndex: 'store'")
    expect(productDetailSource).toContain("{ settingsKey: 'category', title: '品类', dataIndex: 'category'")
    expect(productDetailSource).toContain("{ settingsKey: 'content', title: '评价', dataIndex: 'text', slotName: 'content'")
    expect(productDetailSource).toContain("{ settingsKey: 'publishedAt', title: '发表时间', dataIndex: 'publishedAt', slotName: 'publishedAt'")
    expect(reviewRowsSource).toContain("title: '杯身轻，户外携带方便'")
    expect(reviewRowsSource).toContain("author: 'Nora K.'")
    expect(reviewRowsSource).toContain("text: '杯身轻，户外携带方便，打果汁速度很快。'")
    expect(reviewRowsSource).toContain("publishedAt: '2026-04-28 18:20'")

    expect(productDetailSource).toMatch(/<div v-else-if="activeDetailTab === 'reviews'" class="product-tab-panel">[\s\S]*<QueryFilterPanel class="review-filter-panel">[\s\S]*label="平台"[\s\S]*label="店铺"[\s\S]*label="品类"[\s\S]*label="日期"/)
    expect(productDetailSource).toContain('<a-select v-model="reviewPlatformFilter" placeholder="全部平台" allow-clear class="volc-design-search-item" @change="applyReviewFilters">')
    expect(productDetailSource).toContain('<a-select v-model="reviewStoreFilter" placeholder="全部店铺" allow-clear class="volc-design-search-item" @change="applyReviewFilters">')
    expect(productDetailSource).toContain('<a-select v-model="reviewCategoryFilter" placeholder="全部品类" allow-clear class="volc-design-search-item" @change="applyReviewFilters">')
    expect(productDetailSource).toMatch(/<button[\s\S]*v-for="option in reviewDateQuickOptions"/)
    expect(productDetailSource).toContain(':class="{ \'is-active\': activeReviewDateQuick === option.value }"')
    expect(productDetailSource).toContain('@click="setReviewDateQuick(option.value)"')
    expect(productDetailSource).toContain('<a-range-picker v-model="reviewDateRange" value-format="YYYY-MM-DD" class="review-date-range" @change="handleReviewDateRangeChange" />')
    expect(productDetailSource).toContain('placeholder="搜索评价内容 / 订单号"')
    expect(productDetailSource).toContain('@search="applyReviewFilters"')
    expect(productDetailSource).toContain('@press-enter="applyReviewFilters"')
    expect(productDetailSource).toContain('@clear="applyReviewFilters"')
    expect(productDetailSource).toContain('<QueryActionBar>')
    expect(productDetailSource).toContain('<a-button type="primary" class="volc-design-button" @click="applyReviewFilters">查询</a-button>')
    expect(productDetailSource).toContain('<a-button class="volc-design-button" @click="resetReviewFilters">重置</a-button>')
    expect(productDetailSource).toContain('<a-button class="volc-design-button">导出</a-button>')
    expect(productDetailSource).not.toContain('const reviewRatingFilters')
    expect(productDetailSource).not.toContain('const reviewTypeFilters')
    expect(productDetailSource).not.toContain('const reviewSortFilters')
    expect(productDetailSource).not.toContain('评论类型')
    expect(productDetailSource).not.toContain('开发者回复')
    expect(productDetailSource).not.toContain('最新评价')
    expect(productDetailSource).toMatch(/<ConfigurableDataTable[\s\S]*:columns="reviewColumns"[\s\S]*:default-visible-keys="reviewVisibleColumnKeys"[\s\S]*:data="filteredReviewRows"[\s\S]*row-key="id"[\s\S]*wrapper-class="product-tab-data-table review-table"/)
    expect(productDetailSource).toContain('<template #rating="{ record }">')
    expect(productDetailSource).toContain('<template #content="{ record }">')
    expect(productDetailSource).toContain('<template #publishedAt="{ record }">')
    expect(productDetailSource).not.toContain('<div class="review-table-header">')
    expect(productDetailSource).not.toContain('<div v-for="review in reviewRows" :key="review.id" class="review-table-row">')
    expect(productDetailSource).toContain('<div class="review-rating-cell">')
    expect(productDetailSource).toContain('<div class="review-content-cell">')
    expect(productDetailSource).toContain('<div class="review-time-cell">{{ (record as ProductReviewRow).publishedAt }}</div>')
    expect(productDetailSource).not.toContain('class="review-comment-card"')
    expect(productDetailSource).not.toContain('class="review-comment-list"')

    expect(reviewCardBodyRule).toContain('display: block')
    expect(reviewCardBodyRule).not.toContain('gap:')
    expect(filterPanelRule).toContain('margin-bottom: 14px')
    expect(dateQuickRule).toContain('display: flex')
    expect(dateQuickRule).toContain('height: 32px')
    expect(dateQuickButtonRule).toContain('height: 32px')
    expect(activeDateQuickButtonRule).toContain('background: rgba(22, 93, 255, 0.08)')
    expect(dateRangeRule).toContain('width: 240px')
    expect(filterSearchRule).toContain('width: 300px')
    expect(tableRule).toContain('--workspace-color-bg: var(--color-bg-2)')
    expect(productDetailSource).not.toContain('.review-table :deep(.arco-table-td)')
    expect(ratingCellRule).toContain('flex-direction: column')
    expect(contentCellRule).toContain('line-height: 22px')
    expect(timeCellRule).toContain('font-variant-numeric: tabular-nums')
  })

  it('shows empty states for non-basic tabs while creating a product', () => {
    const emptyRule = getStyleRule('.product-tab-empty')

    expect(productDetailSource).toContain('<div v-if="isCreateMode" class="product-tab-empty">')
    expect(productDetailSource).toContain('<a-empty description="提交商品后可查看库存概况" />')
    expect(productDetailSource).toContain('<a-empty description="提交商品后可查看近期订单" />')
    expect(productDetailSource).toContain('<a-empty description="提交商品后可查看利润概览" />')
    expect(productDetailSource).toContain('<a-empty description="提交商品后可查看商品评价" />')
    expect(productDetailSource).toContain('<a-empty description="提交商品后可查看变更记录" />')
    expect(productDetailSource).toMatch(/<div v-else-if="activeDetailTab === 'inventory'" class="product-tab-panel">[\s\S]*<div v-if="isCreateMode" class="product-tab-empty">[\s\S]*<template v-else>[\s\S]*<MetricSummaryStrip/)
    expect(productDetailSource).toMatch(/<div v-else-if="activeDetailTab === 'changes'" class="product-tab-panel">[\s\S]*<div v-if="isCreateMode" class="product-tab-empty">[\s\S]*<template v-else>[\s\S]*:columns="changeLogColumns"/)
    expect(productDetailSource).not.toContain('class="product-submit-bar"')

    expect(emptyRule).toContain('padding: 56px 0')
    expect(emptyRule).toContain('border: 1px solid var(--product-color-border)')
    expect(emptyRule).toContain('background: var(--color-bg-1)')
  })

  it('renders change records as a clear before-and-after table like the reference', () => {
    const changeLogSource = getConstArraySource('changeLogItems')
    const timeRule = getStyleRule('.change-log-time')
    const timeStrongRule = getStyleRule('.change-log-time strong')
    const timeSmallRule = getStyleRule('.change-log-time small')
    const operatorRule = getStyleRule('.change-log-operator')
    const avatarRule = getStyleRule('.change-log-operator-avatar')
    const fieldRule = getStyleRule('.change-log-field')
    const valueListRule = getStyleRule('.change-log-value-list')
    const valueLineRule = getStyleRule('.change-log-value-line')
    const statusRule = getStyleRule('.change-log-status')
    const statusDotRule = getStyleRule('.change-log-status-dot')
    const tagRule = getStyleRule('.change-log-tag')
    const arrowRule = getStyleRule('.change-log-arrow')

    expect(productDetailSource).toContain('type ChangeLogChange = {')
    expect(productDetailSource).toContain("type ChangeLogColumnKey = 'time' | 'operator' | 'category' | 'before' | 'direction' | 'after'")
    expect(productDetailSource).toContain('type ChangeLogTableColumnData = ConfigurableTableColumn<ChangeLogColumnKey> & { title: string }')
    expect(productDetailSource).toContain('changes: ChangeLogChange[]')
    expect(productDetailSource).toContain('const changeLogVisibleColumnKeys: ChangeLogColumnKey[] = [')
    expect(productDetailSource).toContain('const changeLogColumns: ChangeLogTableColumnData[] = [')
    expect(changeLogSource).toContain("date: '04月30日'")
    expect(changeLogSource).toContain("operator: '张三'")
    expect(changeLogSource).toContain('changes: [')
    expect(changeLogSource).toContain("category: '基础信息', field: '包装尺寸'")
    expect(changeLogSource).toContain("before: '18 × 8 × 4 cm'")
    expect(changeLogSource).toContain("after: '24 × 10.5 × 10.5 cm'")
    expect(changeLogSource).toContain("field: '商品英文名'")
    expect(changeLogSource).toContain("before: 'Portable Blender Cup'")
    expect(changeLogSource).toContain("after: 'Portable Blender Travel Cup'")
    expect(changeLogSource.match(/time: '2026-04-30 00:18'/g)?.length).toBe(1)
    expect(changeLogSource).toContain("field: '最近采购价'")
    expect(changeLogSource).toContain("before: '¥42.00'")
    expect(changeLogSource).toContain("after: '¥49.80'")
    expect(changeLogSource).not.toContain("after: '¥49.80', afterTone:")
    expect(productDetailSource).toContain("type ChangeLogValueType = 'text' | 'status' | 'tag'")
    expect(productDetailSource).toContain('valueType?: ChangeLogValueType')
    expect(changeLogSource).toContain("category: '平台映射', field: '平台', before: '-', after: 'WB', afterTone: 'blue', valueType: 'tag'")
    expect(changeLogSource).toContain("category: '平台映射', field: '店铺', before: '-', after: '中东生活店'")
    expect(changeLogSource).toContain("category: '平台映射', field: '平台商品 ID', before: '-', after: 'WB-PROD-10332'")
    expect(changeLogSource).toContain("category: '平台映射', field: '上架状态', before: '未上架', after: '已上架', beforeTone: 'orange', afterTone: 'green', valueType: 'status'")
    expect(changeLogSource.match(/time: '2026-03-20 09:15'/g)?.length).toBe(1)
    expect(changeLogSource).not.toContain("field: '绑定店铺'")
    expect(changeLogSource).not.toContain("after: 'WB · 中东生活店'")
    expect(changeLogSource).not.toContain("after: 'Wildberries · 中东生活店 · WB-PROD-10332'")
    expect(changeLogSource).toContain("field: '创建商品'")
    expect(changeLogSource).toContain("date: '03月15日'")
    expect(changeLogSource).toContain("time: '2026-03-15 10:30'")
    expect(changeLogSource).toContain("operator: '系统'")
    expect(changeLogSource).toContain("operatorInitial: '系'")
    expect(changeLogSource).toContain("{ category: '商品档案', field: '创建商品', before: '-', after: '-' }")
    expect(changeLogSource).not.toContain("field: '商品档案'")
    expect(changeLogSource).not.toContain("after: '创建商品 SKU-BLEND-001'")

    expect(productDetailSource).toMatch(/<div v-else-if="activeDetailTab === 'changes'" class="product-tab-panel">[\s\S]*<ConfigurableDataTable[\s\S]*:columns="changeLogColumns"[\s\S]*:default-visible-keys="changeLogVisibleColumnKeys"[\s\S]*:data="changeLogItems"[\s\S]*row-key="id"[\s\S]*wrapper-class="product-tab-data-table change-log-table"/)
    expect(productDetailSource).not.toContain('<span>字段</span>')
    expect(productDetailSource).not.toContain('保留商品资料、采购和映射维护轨迹')
    expect(productDetailSource).not.toMatch(/<div v-else-if="activeDetailTab === 'changes'" class="product-tab-panel">[\s\S]*<template #title>[\s\S]*变更记录/)
    expect(productDetailSource).not.toContain('class="change-log-header"')
    expect(productDetailSource).not.toContain('class="change-log-record"')
    expect(productDetailSource).toContain('<template #time="{ record }">')
    expect(productDetailSource).toContain('<template #operator="{ record }">')
    expect(productDetailSource).toContain('<template #category="{ record }">')
    expect(productDetailSource).toContain('<template #before="{ record }">')
    expect(productDetailSource).toContain('<template #direction>')
    expect(productDetailSource).toContain('<template #after="{ record }">')
    expect(productDetailSource).toContain('<div class="change-log-time">')
    expect(productDetailSource).toContain('<strong>{{ (record as ChangeLogItem).date }}</strong>')
    expect(productDetailSource).toContain('<small>{{ (record as ChangeLogItem).time }}</small>')
    expect(productDetailSource).toContain('<div class="change-log-field">{{ (record as ChangeLogItem).changes[0]?.category }}</div>')
    expect(productDetailSource).toContain('<div class="change-log-value-list">')
    expect(productDetailSource).toContain('v-for="change in (record as ChangeLogItem).changes"')
    expect(productDetailSource).not.toContain('class="change-log-change-list"')
    expect(productDetailSource).not.toContain('class="change-log-change"')
    expect(productDetailSource).not.toContain('<div class="change-log-field">{{ change.category }}</div>')
    expect(productDetailSource).toContain('class="change-log-operator-avatar"')
    expect(productDetailSource).toContain('class="change-log-arrow"')
    expect(productDetailSource).toContain('→')
    expect(productDetailSource).toContain('change.valueType === \'status\' && change.beforeTone')
    expect(productDetailSource).toContain('change.valueType === \'status\' && change.afterTone')
    expect(productDetailSource).toContain('class="change-log-status"')
    expect(productDetailSource).toContain('class="change-log-status-dot"')
    expect(productDetailSource).toContain('class="change-log-tag"')
    expect(productDetailSource).toContain('class="change-log-value-label"')
    expect(productDetailSource).toContain('{{ change.field }}：')
    expect(productDetailSource).not.toContain(':class="item.afterTone ? `is-${item.afterTone}` : undefined"')
    expect(productDetailSource).not.toContain('change-log-title')
    expect(productDetailSource).not.toContain('change-log-detail')

    expect(productDetailSource).not.toContain('.change-log-change + .change-log-change')
    expect(timeRule).toContain('display: flex')
    expect(timeRule).toContain('flex-direction: column')
    expect(timeStrongRule).toContain('font-weight: 600')
    expect(timeSmallRule).toContain('font-variant-numeric: tabular-nums')
    expect(operatorRule).toContain('display: inline-flex')
    expect(avatarRule).toContain('width: 32px')
    expect(avatarRule).toContain('border-radius: 50%')
    expect(fieldRule).toContain('font-weight: 600')
    expect(valueListRule).toContain('flex-direction: column')
    expect(valueListRule).toContain('gap: 8px')
    expect(valueListRule).toContain('justify-content: flex-start')
    expect(valueLineRule).toContain('min-height: 22px')
    expect(statusRule).toContain('display: inline-flex')
    expect(statusRule).toContain('gap: 6px')
    expect(statusRule).toContain('padding: 1px 10px')
    expect(statusDotRule).toContain('background: currentColor')
    expect(tagRule).toContain('display: inline-flex')
    expect(arrowRule).toContain('justify-content: center')
  })

  it('reuses the configurable batch-inventory table treatment in product detail table tabs', () => {
    expect(productDetailSource).toContain("type InventoryColumnKey = 'warehouse' | 'location' | 'stock' | 'warningQty' | 'status'")
    expect(productDetailSource).toContain("type RecentOrderColumnKey = 'orderNo' | 'platform' | 'store' | 'quantity' | 'amount' | 'status' | 'orderedAt'")
    expect(productDetailSource).toContain("type ReviewColumnKey = 'rating' | 'platform' | 'store' | 'category' | 'content' | 'publishedAt'")
    expect(productDetailSource).toContain("type ChangeLogColumnKey = 'time' | 'operator' | 'category' | 'before' | 'direction' | 'after'")
    expect(productDetailSource).toContain('const inventoryVisibleColumnKeys: InventoryColumnKey[] = [')
    expect(productDetailSource).toContain('const recentOrderVisibleColumnKeys: RecentOrderColumnKey[] = [')
    expect(productDetailSource).toContain('const reviewVisibleColumnKeys: ReviewColumnKey[] = [')
    expect(productDetailSource).toContain('const changeLogVisibleColumnKeys: ChangeLogColumnKey[] = [')
    expect(productDetailSource).toContain('const getInventoryStoreBadgeLabel = (group: { platform: string }) => group.platform ? getPlatformShortLabel(group.platform) : \'自有仓库\'')
    expect(productDetailSource).toContain("const getInventoryStoreName = (store: string) => store.replace('自有仓库 · ', '')")
    expect(productDetailSource).toMatch(/<div v-else-if="activeDetailTab === 'inventory'" class="product-tab-panel">[\s\S]*<ConfigurableDataTable[\s\S]*:columns="inventoryColumns"[\s\S]*:default-visible-keys="inventoryVisibleColumnKeys"[\s\S]*table-class="data-table"[\s\S]*wrapper-class="product-tab-data-table"/)
    expect(productDetailSource).toMatch(/<div class="product-tab-card-title">[\s\S]*<span class="mapping-platform-badge">[\s\S]*{{ getInventoryStoreBadgeLabel\(group\) }}[\s\S]*<span>{{ getInventoryStoreName\(group.store\) }}<\/span>/)
    expect(productDetailSource).not.toContain('<span v-if="group.platform" class="mapping-platform-badge">')
    expect(productDetailSource).toMatch(/<div v-else-if="activeDetailTab === 'orders'" class="product-tab-panel">[\s\S]*<ConfigurableDataTable[\s\S]*:columns="recentOrderColumns"[\s\S]*:default-visible-keys="recentOrderVisibleColumnKeys"[\s\S]*table-class="data-table"[\s\S]*wrapper-class="product-tab-data-table"/)
    expect(productDetailSource).not.toContain('const profitVisibleColumnKeys: ProfitColumnKey[] = [')
    expect(productDetailSource).not.toContain('const profitColumns: ProfitTableColumnData[] = [')
    expect(productDetailSource).not.toMatch(/<div v-else-if="activeDetailTab === 'profit'" class="product-tab-panel">[\s\S]*<ConfigurableDataTable[\s\S]*:columns="profitColumns"/)
    expect(productDetailSource).toMatch(/<div v-else-if="activeDetailTab === 'reviews'" class="product-tab-panel">[\s\S]*<ConfigurableDataTable[\s\S]*:columns="reviewColumns"[\s\S]*:default-visible-keys="reviewVisibleColumnKeys"[\s\S]*table-class="data-table"[\s\S]*wrapper-class="product-tab-data-table review-table"/)
    expect(productDetailSource).toMatch(/<div v-else-if="activeDetailTab === 'changes'" class="product-tab-panel">[\s\S]*<ConfigurableDataTable[\s\S]*:columns="changeLogColumns"[\s\S]*:default-visible-keys="changeLogVisibleColumnKeys"[\s\S]*table-class="data-table"[\s\S]*wrapper-class="product-tab-data-table change-log-table"/)
    expect(productDetailSource).not.toMatch(/<div v-else-if="activeDetailTab === 'orders'" class="product-tab-panel">[\s\S]*<a-table[\s\S]*:columns="recentOrderColumns"/)
    expect(productDetailSource).not.toContain('wrapper-class="mapping-table product-tab-table')
    expect(productDetailSource).not.toContain('class="change-log-header"')
  })

  it('matches the prototype metric data for inventory, orders, and profit tabs', () => {
    const inventorySummarySource = getConstArraySource('inventorySummaryCards')
    const recentOrderSummarySource = getConstArraySource('recentOrderSummaryCards')
    const profitSummarySource = getConstArraySource('profitSummaryCards')

    expect(inventorySummarySource).toContain("{ label: '总库存', value: '156', note: '4 个店铺 · 7 个仓库' }")
    expect(inventorySummarySource).toContain("{ label: 'WB 仓库合计', value: '98', note: '3 个店铺', tone: 'blue' }")
    expect(inventorySummarySource).toContain("{ label: '自有仓库合计', value: '58', note: '1 个仓库' }")
    expect(inventorySummarySource).toContain("{ label: '低库存预警', value: '2', note: '白俄仓 / 深圳仓', tone: 'red' }")

    expect(recentOrderSummarySource).toContain("{ label: '近 30 天订单', value: '32' }")
    expect(recentOrderSummarySource).toContain("{ label: '待发货', value: '5', tone: 'orange' }")
    expect(recentOrderSummarySource).toContain("{ label: '运输中', value: '12', tone: 'blue' }")
    expect(recentOrderSummarySource).toContain("{ label: '已完成', value: '15', tone: 'green' }")

    expect(profitSummarySource).toContain("{ label: '近 30 天销售额', value: '68 230 ₽', note: '36 笔订单', tone: 'blue' }")
    expect(profitSummarySource).toContain("{ label: '近 30 天采购成本', value: '¥ 1 620', note: '36 件 × ¥45' }")
    expect(profitSummarySource).toContain("{ label: '近 30 天净利润率', value: '52.3%', note: '汇率 8.72 CNY/RUB', tone: 'green' }")

    expect(productDetailSource).toMatch(/<MetricSummaryStrip[\s\S]*class="product-tab-summary-strip"[\s\S]*:cards="inventorySummaryCards"[\s\S]*:columns="4"/)
    expect(productDetailSource).toMatch(/<MetricSummaryStrip[\s\S]*class="product-tab-summary-strip"[\s\S]*:cards="recentOrderSummaryCards"[\s\S]*:columns="4"/)
    expect(productDetailSource).toMatch(/<MetricSummaryStrip[\s\S]*class="product-tab-summary-strip"[\s\S]*:cards="profitSummaryCards"[\s\S]*:columns="3"/)
    expect(productDetailSource).not.toContain('class="product-tab-summary-grid')
    expect(productDetailSource).not.toContain('class="product-tab-stat-card"')
  })

  it('matches prototype rows for inventory, recent orders, and profit cards', () => {
    const inventoryGroupSource = getConstArraySource('inventoryStoreGroups')
    const recentOrderRowsSource = getConstArraySource('recentOrderRows')
    const profitRowsSource = getConstArraySource('profitRows')

    expect(inventoryGroupSource).toContain("store: '俄区主店'")
    expect(inventoryGroupSource).toContain("store: '哈萨克斯坦店'")
    expect(inventoryGroupSource).toContain("store: '白俄罗斯店'")
    expect(inventoryGroupSource).toContain("warehouse: 'WB 莫斯科仓'")
    expect(inventoryGroupSource).toContain("warehouse: 'WB 圣彼得堡仓'")
    expect(inventoryGroupSource).toContain("warehouse: 'WB 阿拉木图仓'")
    expect(inventoryGroupSource).toContain("warehouse: 'WB 明斯克仓'")

    expect(recentOrderRowsSource).toContain("orderNo: 'WB-78901234', platform: 'Wildberries', store: '俄区主店', quantity: 1, amount: '1 890 ₽', status: '已完成', statusTone: 'green', orderedAt: '04-28'")
    expect(recentOrderRowsSource).toContain("orderNo: 'WB-78901198', platform: 'Wildberries', store: '哈萨克斯坦店', quantity: 2, amount: '15 800 ₽', status: '待发货', statusTone: 'orange', orderedAt: '04-29'")
    expect(recentOrderRowsSource).toContain("orderNo: 'WB-78900845', platform: 'Wildberries', store: '俄区主店', quantity: 3, amount: '5 670 ₽', status: '已完成', statusTone: 'green', orderedAt: '04-25'")
    expect(recentOrderRowsSource).toContain("orderNo: 'WB-78900612', platform: 'Wildberries', store: '哈萨克斯坦店', quantity: 1, amount: '7 900 ₽', status: '运输中', statusTone: 'blue', orderedAt: '04-24'")

    expect(profitRowsSource).toContain("store: '俄区主店'")
    expect(profitRowsSource).toContain("store: '哈萨克斯坦店'")
    expect(profitRowsSource).toContain("platform: 'WB'")
    expect(profitRowsSource).toContain("price: '1 890 ₽'")
    expect(profitRowsSource).toContain("discount: '-10%'")
    expect(profitRowsSource).toContain("dealPrice: '1 701 ₽'")
    expect(profitRowsSource).toContain("commission: '- 255 ₽'")
    expect(profitRowsSource).toContain("logisticsFee: '- 85 ₽'")
    expect(profitRowsSource).toContain("purchaseCost: '- 392 ₽ (¥45)'")
    expect(profitRowsSource).toContain("netProfit: '+ 969 ₽'")
    expect(profitRowsSource).toContain("profitRate: '77.2%'")
  })

  it('uses the batch inventory metric strip styling for product tab data blocks', () => {
    const summaryStripRule = getStyleRule('.product-tab-summary-strip')
    const metricStripRule = getMetricSummaryStyleRule('.metric-summary-strip')
    const metricItemRule = getMetricSummaryStyleRule('.metric-summary-item')

    expect(summaryStripRule).toContain('--workspace-color-bg: var(--color-bg-1)')
    expect(summaryStripRule).toContain('--workspace-color-border: var(--product-color-border)')
    expect(summaryStripRule).toContain('--workspace-color-text: var(--product-color-text)')
    expect(summaryStripRule).toContain('--workspace-color-text-secondary: var(--product-color-text-secondary)')
    expect(summaryStripRule).toContain('--workspace-color-text-tertiary: var(--product-color-text-tertiary)')
    expect(metricStripRule).not.toContain('height:')
    expect(metricStripRule).not.toContain('min-height:')
    expect(metricItemRule).not.toContain('min-height:')
    expect(metricItemRule).not.toContain('height:')
    expect(metricItemRule).toContain('padding: 18px 28px')
  })

  it('renders profit values as cards instead of a shared table', () => {
    const profitGridRule = getStyleRule('.profit-card-grid')
    const profitCardRule = getStyleRule('.profit-overview-card')
    const profitHeaderTitleRule = getStyleRule('.profit-overview-header h3')
    const profitRowRule = getStyleRule('.profit-overview-row')
    const profitRowLabelRule = getStyleRule('.profit-overview-row span')
    const profitValueRule = getStyleRule('.profit-value')

    expect(productDetailSource).toContain('<div class="profit-card-grid">')
    expect(productDetailSource).toContain('v-for="row in profitRows"')
    expect(productDetailSource).toContain('class="profit-overview-card"')
    expect(productDetailSource).toContain('{{ row.platform }}')
    expect(productDetailSource).toContain('<h3>{{ row.store }}</h3>')
    expect(productDetailSource).toContain('class="profit-overview-row"')
    expect(productDetailSource).toContain('class="profit-overview-divider"')
    expect(productDetailSource).toContain('class="profit-value is-negative"')
    expect(productDetailSource).toContain('class="profit-value is-positive"')
    expect(productDetailSource).not.toContain('<template #commission="{ record }">')
    expect(productDetailSource).not.toContain('<template #netProfit="{ record }">')
    expect(profitGridRule).toContain('display: grid')
    expect(profitGridRule).toContain('grid-template-columns: repeat(auto-fit, minmax(360px, 1fr))')
    expect(profitCardRule).toContain('border: 1px solid var(--product-color-border)')
    expect(profitCardRule).toContain('background: var(--color-bg-1)')
    expect(profitCardRule).toContain('box-shadow: 0 8px 24px rgba(15, 23, 42, 0.06)')
    expect(profitHeaderTitleRule).toContain('font-size: 14px')
    expect(profitHeaderTitleRule).toContain('line-height: 22px')
    expect(profitRowRule).toContain('grid-template-columns: minmax(0, 1fr) auto')
    expect(profitRowRule).toContain('min-height: 32px')
    expect(profitRowLabelRule).toContain('font-size: 13px')
    expect(profitRowLabelRule).toContain('line-height: 20px')
    expect(profitValueRule).toContain('text-align: right')
    expect(profitValueRule).toContain('font-weight: 500')
    expect(profitValueRule).toContain('font-size: 13px')
    expect(profitValueRule).toContain('line-height: 20px')
    expect(profitValueRule).toContain('font-variant-numeric: tabular-nums')
  })

  it('reuses the previous warehouse inventory tab treatment', () => {
    const tabsRule = getStyleRule('.product-detail-tabs')
    const tabsLineRule = getStyleRule('.product-detail-tabs::before')
    const tabRule = getStyleRule('.product-detail-tab')
    const firstTabRule = getStyleRule('.product-detail-tab:first-child')
    const tabBottomRule = getStyleRule('.product-detail-tab::after')
    const activeTabRule = getStyleRule('.product-detail-tab.is-active')
    const activeTabBottomRule = getStyleRule('.product-detail-tab.is-active::after')

    expect(tabsRule).toContain('align-items: flex-end')
    expect(tabsRule).toContain('border-bottom: 0')
    expect(tabsRule).not.toContain('background: var(--color-bg-2)')
    expect(tabsLineRule).toContain('right: calc(var(--product-tabs-line-bleed) * -1)')
    expect(tabsLineRule).toContain('left: calc(var(--product-tabs-line-bleed) * -1)')
    expect(tabsLineRule).toContain('height: 1px')
    expect(tabsLineRule).toContain('background: var(--product-color-border)')
    expect(tabsLineRule).toContain("content: ''")

    expect(tabRule).toContain('z-index: 1')
    expect(tabRule).toContain('margin: 0 0 0 4px')
    expect(tabRule).toContain('padding: 7px 16px')
    expect(tabRule).toContain('border: 0')
    expect(tabRule).toContain('border-radius: var(--product-radius-small) var(--product-radius-small) 0 0')
    expect(tabRule).toContain('box-shadow:')
    expect(tabRule).toContain('inset 0 1px 0 var(--product-color-border)')
    expect(tabRule).toContain('inset -1px 0 0 var(--product-color-border)')
    expect(tabRule).toContain('inset 1px 0 0 var(--product-color-border)')
    expect(firstTabRule).toContain('margin-left: 0')
    expect(tabBottomRule).toContain('width: calc(100% - 2px)')
    expect(tabBottomRule).toContain('background: var(--product-color-border)')

    expect(activeTabRule).toContain('box-shadow:')
    expect(activeTabRule).toContain('inset 0 2px 0 var(--product-color-primary)')
    expect(activeTabRule).toContain('inset -1px 0 0 var(--product-color-border)')
    expect(activeTabRule).toContain('inset 1px 0 0 var(--product-color-border)')
    expect(activeTabRule).toContain('background: var(--product-color-bg)')
    expect(activeTabRule).toContain('color: var(--product-color-primary)')
    expect(activeTabBottomRule).toContain('background: var(--product-color-bg)')
  })

  it('keeps only the product status tag in the overview title row', () => {
    expect(productDetailSource).toContain('<a-tag v-if="draft.basicInfo.status" :color="statusToneMap[draft.basicInfo.status]">{{ statusLabelMap[draft.basicInfo.status] }}</a-tag>')
    expect(productDetailSource).not.toContain("draft.procurement.purchasable ? '可采购' : '不可采购'")
    expect(productDetailSource).not.toContain("draft.basicInfo.category || '未选类目'")
  })

  it('renders product detail sections as flat content under the tabs', () => {
    const pageRule = getStyleRule('.product-detail-page')
    const tabsRule = getStyleRule('.product-detail-tabs')
    const overviewRule = getStyleRule('.overview-card')
    const sectionCardRule = getProductSectionStyleRule('.product-section-card')
    const sectionHeaderRule = getProductSectionStyleRule('.product-section-card :deep\\(.arco-card-header\\)')
    const sectionBodyRule = getProductSectionStyleRule('.product-section-card :deep\\(.arco-card-body\\)')

    expect(pageRule).toContain('gap: 0')
    expect(tabsRule).toContain('margin-bottom: 0')
    expect(overviewRule).toContain('margin-top: 16px')
    expect(productDetailSource).not.toContain('class="sticky-footer"')
    expect(productDetailSource).not.toContain('.sticky-footer')
    expect(productDetailSource).not.toContain('@click="saveProduct(false)"')
    expect(productDetailSource).not.toContain('@click="saveProduct(true)"')
    expect(productDetailSource).not.toContain('保存并返回')

    expect(sectionCardRule).toContain('overflow: visible')
    expect(sectionCardRule).toContain('border: 0')
    expect(sectionCardRule).toContain('border-radius: 0')
    expect(sectionCardRule).toContain('background: transparent')
    expect(sectionCardRule).not.toContain('border: 1px solid')

    expect(sectionHeaderRule).toContain('padding: 24px 0 8px')
    expect(sectionHeaderRule).not.toContain('padding: 24px 16px 8px')
    expect(sectionHeaderRule).toContain('border-bottom: 0')
    expect(sectionBodyRule).toContain('padding: 14px 0 0')
    expect(sectionBodyRule).not.toContain('padding: 14px 16px 0')
  })

  it('uses a light-bordered overview card without color-bg-3 fill', () => {
    const overviewCardRule = getStyleRule('.overview-card')

    expect(overviewCardRule).toContain('min-height: 104px')
    expect(overviewCardRule).toContain('padding: 20px 28px')
    expect(overviewCardRule).toContain('border: 1px solid var(--product-color-border)')
    expect(overviewCardRule).toContain('background: transparent')
    expect(overviewCardRule).not.toContain('background: var(--color-bg-3)')
  })

  it('keeps the overview card visually compact like the reference console card', () => {
    expect(productDetailSource).toContain('width: 64px')
    expect(productDetailSource).toContain('height: 64px')
    expect(productDetailSource).toContain('font-size: 18px')
    expect(productDetailSource).not.toContain('min-height: 152px')
    expect(productDetailSource).not.toContain('padding: 32px 44px')
    expect(productDetailSource).not.toContain('font-size: 24px')
    expect(productDetailSource).not.toContain('font-size: 26px')
  })
})
