import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

const navigationSource = readFileSync(
  new URL('../src/data/navigation.ts', import.meta.url),
  'utf-8',
)

const routerSource = readFileSync(
  new URL('../src/router/index.ts', import.meta.url),
  'utf-8',
)

const listViewSource = readFileSync(
  new URL('../src/views/StoreAdvertisingView.vue', import.meta.url),
  'utf-8',
)

const detailViewSource = readFileSync(
  new URL('../src/views/StoreAdvertisingDetailView.vue', import.meta.url),
  'utf-8',
)

const statisticsViewSource = readFileSync(
  new URL('../src/views/StoreAdvertisingStatisticsView.vue', import.meta.url),
  'utf-8',
)

const workbenchSource = readFileSync(
  new URL('../src/components/stores/StoreAdvertisingWorkbench.vue', import.meta.url),
  'utf-8',
)

const detailWorkbenchSource = readFileSync(
  new URL('../src/components/stores/StoreAdvertisingDetailWorkbench.vue', import.meta.url),
  'utf-8',
)

const statisticsWorkbenchSource = readFileSync(
  new URL('../src/components/stores/StoreAdvertisingStatisticsWorkbench.vue', import.meta.url),
  'utf-8',
)

const styleSource = readFileSync(
  new URL('../src/components/stores/storeAdvertising.css', import.meta.url),
  'utf-8',
)

describe('store advertising source contracts', () => {
  it('wires advertising navigation to real routes', () => {
    expect(navigationSource).toContain("{ key: 'ads', title: '广告推广', path: '/stores/ads'")
    expect(routerSource).toContain("import StoreAdvertisingView from '../views/StoreAdvertisingView.vue'")
    expect(routerSource).toContain("import StoreAdvertisingDetailView from '../views/StoreAdvertisingDetailView.vue'")
    expect(routerSource).toContain("import StoreAdvertisingStatisticsView from '../views/StoreAdvertisingStatisticsView.vue'")
    expect(routerSource).toContain("&& item.path !== '/stores/ads'")
    expect(routerSource).toMatch(/path:\s*'stores\/ads'[\s\S]*?component:\s*StoreAdvertisingView/)
    expect(routerSource).toMatch(/path:\s*'stores\/ads\/:campaignId\/statistics'[\s\S]*?component:\s*StoreAdvertisingStatisticsView/)
    expect(routerSource).toMatch(/path:\s*'stores\/ads\/:campaignId'[\s\S]*?component:\s*StoreAdvertisingDetailView/)
  })

  it('keeps route views thin', () => {
    expect(listViewSource).toContain('<StoreAdvertisingWorkbench />')
    expect(detailViewSource).toContain(':campaign-id="campaignId"')
    expect(statisticsViewSource).toContain(':campaign-id="campaignId"')
  })

  it('renders the advertising homepage shell', () => {
    expect(workbenchSource).toContain('广告推广')
    expect(workbenchSource).toContain('平台')
    expect(workbenchSource).toContain('店铺')
    expect(workbenchSource).toContain('ConfigurableDataTable')
    expect(workbenchSource).toContain('router.push(`/stores/ads/${record.id}`)')
    expect(workbenchSource).toContain('router.push(`/stores/ads/${record.id}/statistics`)')
    expect(workbenchSource).toContain('创建活动')
    expect(workbenchSource).not.toContain('统一查看多平台、多店铺广告活动、预算消耗与转化表现。')
  })

  it('uses the product metadata filter layout on the homepage', () => {
    expect(workbenchSource).toContain("import QueryActionBar from '../common/QueryActionBar.vue'")
    expect(workbenchSource).toContain("import QueryFilterItem from '../common/QueryFilterItem.vue'")
    expect(workbenchSource).toContain("import QueryFilterPanel from '../common/QueryFilterPanel.vue'")
    expect(workbenchSource).not.toContain('class="advertising-scope-picker"')
    expect(workbenchSource).not.toContain('class="advertising-scope-select"')
    expect(workbenchSource).not.toContain('resolveAdvertisingScopeLabel')
    expect(workbenchSource).not.toContain('广告范围')
    expect(workbenchSource).toContain('v-model="filters.storeIds"')
    expect(workbenchSource).toContain('v-for="option in storeOptions"')
    expect(workbenchSource).toMatch(/class="advertising-page-header-actions"[\s\S]*?创建活动/)
    expect(workbenchSource).not.toMatch(/class="advertising-page-header-actions"[\s\S]*?刷新/)
    expect(workbenchSource).not.toContain('IconRefresh')
    expect(workbenchSource).not.toContain('refreshData')
    expect(workbenchSource).not.toContain('<section class="advertising-scope-bar">')
    expect(workbenchSource).not.toContain('<MetricSummaryStrip')
    expect(workbenchSource).toContain('<QueryFilterPanel class="advertising-filter-panel">')
    expect(workbenchSource).toContain('<QueryFilterItem label="关键词"')
    expect(workbenchSource).toContain('<QueryFilterItem label="店铺"')
    expect(workbenchSource).toContain('<QueryFilterItem label="日期"')
    expect(workbenchSource).toContain('<QueryFilterItem label="活动状态"')
    expect(workbenchSource).toContain('<QueryFilterItem label="活动类型"')
    expect(workbenchSource).toContain('<QueryFilterItem label="预算状态"')
    expect(workbenchSource).toMatch(/<QueryFilterItem label="关键词"[\s\S]*?<QueryFilterItem label="店铺" width="320px" min-width="300px"[\s\S]*?<QueryFilterItem label="活动状态" width="280px" min-width="260px"[\s\S]*?<QueryFilterItem label="活动类型" width="260px" min-width="240px"[\s\S]*?<QueryFilterItem label="预算状态" width="320px" min-width="300px"[\s\S]*?<QueryFilterItem label="日期" width="300px" min-width="260px"[\s\S]*?<QueryActionBar>/)
    expect(workbenchSource).toContain('const filterSelectWidths = ref')
    expect(workbenchSource).toContain('const resolveFilterMaxTagCount = (selectedLabels: string[], availableWidth: number)')
    expect(workbenchSource).toContain('ResizeObserver')
    expect(workbenchSource).toMatch(/<QueryFilterItem label="店铺"[\s\S]*?data-filter-key="storeIds"[\s\S]*?:max-tag-count="storeFilterMaxTagCount"[\s\S]*?<QueryFilterItem label="活动状态"[\s\S]*?data-filter-key="statuses"[\s\S]*?:max-tag-count="statusFilterMaxTagCount"[\s\S]*?<QueryFilterItem label="活动类型"[\s\S]*?data-filter-key="campaignTypes"[\s\S]*?:max-tag-count="campaignTypeFilterMaxTagCount"[\s\S]*?<QueryFilterItem label="预算状态"[\s\S]*?data-filter-key="budgetStatuses"[\s\S]*?:max-tag-count="budgetStatusFilterMaxTagCount"/)
    expect(workbenchSource).not.toContain(':max-tag-count="1"')
    expect(workbenchSource).not.toContain(':max-tag-count="2"')
    expect(workbenchSource).toContain('<QueryActionBar>')
    expect(workbenchSource).not.toContain('@click="filterActiveCampaigns"')
    expect(workbenchSource).not.toContain('const filterActiveCampaigns')
    expect(workbenchSource).not.toContain('class="advertising-activity-toolbar"')
    expect(workbenchSource).not.toContain('class="advertising-filter-row"')
    expect(workbenchSource).not.toContain('<h2>活动</h2>')
    expect(workbenchSource).not.toContain('class="advertising-toolbar-primary"')
    expect(workbenchSource).not.toContain('class="advertising-toolbar-actions"')
    expect(workbenchSource).toContain('通过活动ID或名称搜索')
    expect(workbenchSource).not.toContain('筛选器')
    expect(workbenchSource).not.toContain('IconFilter')
    expect(workbenchSource).not.toContain('advancedFiltersVisible')
  })

  it('shows campaign sample images with product count badges', () => {
    expect(workbenchSource).toContain("import { useProductCatalogStore } from '../../data/productCatalog'")
    expect(workbenchSource).toContain('const catalogStore = useProductCatalogStore()')
    expect(workbenchSource).toContain('const productBySku = computed')
    expect(workbenchSource).toContain('const getAdvertisingProductImage = (product?: AdvertisingCampaignProduct)')
    expect(workbenchSource).toContain('<a-badge')
    expect(workbenchSource).toContain(':count="record.products.length"')
    expect(workbenchSource).toContain('class="advertising-campaign-main"')
    expect(workbenchSource).toContain('class="advertising-campaign-thumb-badge"')
    expect(workbenchSource).toContain('class="advertising-campaign-image"')
    expect(workbenchSource).toContain(':src="getAdvertisingProductImage(record.products[0])"')
    expect(workbenchSource).not.toContain("record.platform.slice(0, 2)")
  })

  it('renders campaign statuses with Arco tags', () => {
    expect(workbenchSource).toContain('<a-tag :color="getCampaignStatusTagColor(record.status)">')
    expect(detailWorkbenchSource).toContain('<a-tag size="small" :color="getCampaignStatusTagColor(campaign.status)">')
    expect(statisticsWorkbenchSource).toContain('<a-tag :color="getCampaignStatusTagColor(campaign.status)">')
    expect(workbenchSource).toContain('getCampaignStatusTagColor')
    expect(detailWorkbenchSource).toContain('getCampaignStatusTagColor')
    expect(statisticsWorkbenchSource).toContain('getCampaignStatusTagColor')
    expect(workbenchSource).not.toContain('class="advertising-status-pill"')
    expect(detailWorkbenchSource).not.toContain('class="advertising-status-pill"')
    expect(statisticsWorkbenchSource).not.toContain('class="advertising-status-pill"')
    expect(workbenchSource).not.toContain('getCampaignStatusClass')
    expect(detailWorkbenchSource).not.toContain('getCampaignStatusClass')
    expect(statisticsWorkbenchSource).not.toContain('getCampaignStatusClass')
    expect(workbenchSource).not.toContain('<span class="advertising-status-pill"')
    expect(detailWorkbenchSource).not.toContain('<span class="advertising-status-pill"')
    expect(statisticsWorkbenchSource).not.toContain('<span class="advertising-status-pill"')
  })

  it('supports advertising campaign bulk selection actions', () => {
    expect(workbenchSource).toContain('const selectedRowKeys = ref')
    expect(workbenchSource).toContain('const currentPage = ref(1)')
    expect(workbenchSource).toContain('const pageSize = ref(10)')
    expect(workbenchSource).toContain('const pagedRows = computed')
    expect(workbenchSource).toContain('const selectablePagedRows = computed')
    expect(workbenchSource).toContain('const campaignRowSelection = {')
    expect(workbenchSource).toContain('v-model:selected-keys="selectedRowKeys"')
    expect(workbenchSource).toContain(':row-selection="campaignRowSelection"')
    expect(workbenchSource).toContain(':data="selectablePagedRows"')
    expect(workbenchSource).toContain('disabled: !isCampaignStatusEditable(row.status)')
    expect(workbenchSource).toContain('const selectableRowKeySet = new Set(rows.filter((row) => isCampaignStatusEditable(row.status)).map((row) => row.id))')
    expect(workbenchSource).toContain('selectedRowKeys.value = selectedRowKeys.value.filter((rowKey) => selectableRowKeySet.has(String(rowKey)))')
    expect(workbenchSource).toContain("{ settingsKey: 'campaign', title: '活动', dataIndex: 'campaign', slotName: 'campaign', width: 320, minWidth: 300")
    expect(workbenchSource).toContain('<template #footer>')
    expect(workbenchSource).toContain('class="advertising-table-footer-row"')
    expect(workbenchSource).toContain('class="advertising-bulk-action-bar"')
    expect(workbenchSource).toContain('已选 <span>{{ selectedRowKeys.length }}</span> / {{ filteredRows.length }} 条')
    expect(workbenchSource).toContain('class="advertising-bulk-action-placeholder"')
    expect(workbenchSource).toContain('取消选择')
    expect(workbenchSource).toContain('批量关闭')
    expect(workbenchSource).toContain('批量开启')
    expect(workbenchSource).toContain("bulkUpdateSelectedCampaigns('paused')")
    expect(workbenchSource).toContain("bulkUpdateSelectedCampaigns('active')")
    expect(workbenchSource).toContain("{ title: '操作', slotName: 'operation', width: 160, minWidth: 148, align: 'center' }")
    expect(workbenchSource).toContain('class="advertising-operation-actions"')
    expect(workbenchSource).toContain('<a-pagination')
    expect(workbenchSource).toContain('v-model:current="currentPage"')
    expect(workbenchSource).toContain('v-model:page-size="pageSize"')
    expect(workbenchSource).toContain('class="advertising-pagination"')
    expect(workbenchSource).toContain(':total="filteredRows.length"')
    expect(workbenchSource).toContain(':page-size-options="[10, 20, 50]"')
    expect(workbenchSource).not.toContain('<section v-if="selectedRowKeys.length" class="advertising-bulk-action-bar">')
  })

  it('keeps the campaign status switch in a standalone table column', () => {
    expect(workbenchSource).toContain("{ title: '', slotName: 'statusToggle', width: 64, minWidth: 56, align: 'center', fixed: 'left' }")
    expect(workbenchSource).toContain('<template #statusToggle="{ record }">')
    expect(workbenchSource).toContain('class="advertising-status-toggle-cell"')
    expect(workbenchSource).not.toMatch(/<template #campaign="\{ record \}">[\s\S]*?<a-switch/)
  })

  it('right aligns the create campaign modal footer actions', () => {
    expect(workbenchSource).toMatch(/<template #footer>[\s\S]*?class="advertising-create-modal-footer"/)
    expect(styleSource).toContain('.advertising-create-modal-footer')
    expect(styleSource).toMatch(/\.advertising-create-modal-footer\s*{[^}]*justify-content: flex-end;/)
  })

  it('renders the advertising detail shell', () => {
    expect(detailWorkbenchSource).toContain("import { Message, type TableColumnData } from '@arco-design/web-vue'")
    expect(detailWorkbenchSource).toContain('IconCopy')
    expect(detailWorkbenchSource).toContain('IconEdit')
    expect(detailWorkbenchSource).toContain("import SecondaryPageHeader from '../common/SecondaryPageHeader.vue'")
    expect(detailWorkbenchSource).toContain('<SecondaryPageHeader')
    expect(detailWorkbenchSource).toContain('title="活动详情"')
    expect(detailWorkbenchSource).not.toContain('title="广告详情"')
    expect(detailWorkbenchSource).toContain('const campaignNameOverride = ref')
    expect(detailWorkbenchSource).toContain('const copyCampaignId = async () =>')
    expect(detailWorkbenchSource).toContain('navigator.clipboard.writeText(campaign.value.id)')
    expect(detailWorkbenchSource).toContain("Message.success(`已复制 ${campaign.value.id}`)")
    expect(detailWorkbenchSource).toContain('const showChangeHistory = () =>')
    expect(detailWorkbenchSource).toContain("import AppEChart from '../common/AppEChart.vue'")
    expect(detailWorkbenchSource).toContain("import type { EChartsOption } from 'echarts'")
    expect(detailWorkbenchSource).toContain('type AdvertisingStatisticsMetricKey')
    expect(detailWorkbenchSource).toContain("type DetailMetricKey = AdvertisingStatisticsMetricKey | 'spendRatio'")
    expect(detailWorkbenchSource).toContain("type DetailMetricTrend = 'up' | 'down' | 'flat'")
    expect(detailWorkbenchSource).not.toContain('DetailMetricTone')
    expect(detailWorkbenchSource).toContain('const selectedDetailMetrics = ref<DetailMetricKey[]>')
    expect(detailWorkbenchSource).toContain('const selectedDetailDateRange = ref<string[]>([])')
    expect(detailWorkbenchSource).toContain('const budgetAutoTopUpEnabled = ref(false)')
    expect(detailWorkbenchSource).toContain('const filteredSummaryPoints = computed(() => {')
    expect(detailWorkbenchSource).toContain('const [startDate, endDate] = selectedDetailDateRange.value')
    expect(detailWorkbenchSource).toContain('return summaryPoints.value.filter((point) => point.date >= startDate && point.date <= endDate)')
    expect(detailWorkbenchSource).toContain('const detailStatisticCards = computed')
    expect(detailWorkbenchSource).toMatch(/title: '点击次数'[\s\S]*metricKey: 'clicks'[\s\S]*color: '#24E0FF'/)
    expect(detailWorkbenchSource).toMatch(/title: '花费比例'[\s\S]*metricKey: 'spendRatio'[\s\S]*value: formatAdvertisingPercent\(record\.budget > 0 \? record\.spend \/ record\.budget \* 100 : 0\)/)
    expect(detailWorkbenchSource).not.toContain('tone:')
    expect(detailWorkbenchSource).toContain('watch(campaign, (nextCampaign) => {')
    expect(detailWorkbenchSource).toContain("budgetAutoTopUpEnabled.value = nextCampaign?.budgetStatus === 'healthy'")
    expect(detailWorkbenchSource).toContain('selectedDetailDateRange.value = nextCampaign ? [nextCampaign.startDate, nextCampaign.endDate] : []')
    expect(detailWorkbenchSource).toContain('const toggleDetailMetric = (metricKey: DetailMetricKey) =>')
    expect(detailWorkbenchSource).toContain('currentMetrics.includes(metricKey)')
    expect(detailWorkbenchSource).toContain('const detailChartOption = computed<EChartsOption>')
    expect(detailWorkbenchSource).toContain('const points = filteredSummaryPoints.value')
    expect(detailWorkbenchSource).toContain('const getDetailMetricPointValue = (point: AdvertisingMetricPoint, metricKey: DetailMetricKey) =>')
    expect(detailWorkbenchSource).toContain("metricKey === 'spendRatio'")
    expect(detailWorkbenchSource).toContain('const shouldFormatPercent = activeCards.length === 1 && activeCards[0]?.metricKey === \'spendRatio\'')
    expect(detailWorkbenchSource).toContain('const detailChartUpdateOptions = { replaceMerge: [\'series\', \'xAxis\', \'yAxis\', \'dataZoom\'] }')
    expect(detailWorkbenchSource).toContain(':update-options="detailChartUpdateOptions"')
    expect(detailWorkbenchSource).not.toContain('legend: {')
    expect(detailWorkbenchSource).not.toContain('data: activeCards.map((card) => card.title)')
    expect(detailWorkbenchSource).toContain('class="advertising-detail-overview-card"')
    expect(detailWorkbenchSource).toContain('class="advertising-detail-overview-main"')
    expect(detailWorkbenchSource).toContain('class="advertising-detail-overview-profile"')
    expect(detailWorkbenchSource).toContain('class="advertising-detail-overview-thumb"')
    expect(detailWorkbenchSource).not.toContain('class="advertising-detail-overview-thumb-badge"')
    expect(detailWorkbenchSource).not.toContain(':count="campaign.products.length"')
    expect(detailWorkbenchSource).toContain(':src="getAdvertisingProductImage(campaign.products[0])"')
    expect(detailWorkbenchSource).toContain('class="advertising-detail-overview-title-row"')
    expect(detailWorkbenchSource).toContain('class="advertising-detail-title-edit-button"')
    expect(detailWorkbenchSource).toContain('@click="openCampaignNameEditor"')
    expect(detailWorkbenchSource).toContain('class="advertising-detail-overview-description advertising-detail-meta-row"')
    expect(detailWorkbenchSource).toContain('class="advertising-detail-meta-id"')
    expect(detailWorkbenchSource).toContain('class="advertising-detail-id-copy-button"')
    expect(detailWorkbenchSource).toContain('@click="copyCampaignId"')
    expect(detailWorkbenchSource).toContain('<icon-copy />')
    expect(detailWorkbenchSource).toContain('class="advertising-detail-history-button"')
    expect(detailWorkbenchSource).toContain('@click="showChangeHistory"')
    expect(detailWorkbenchSource).toContain('变更历史')
    expect(detailWorkbenchSource).toContain('class="advertising-detail-overview-actions"')
    expect(detailWorkbenchSource).toContain('class="advertising-detail-overview-divider"')
    expect(detailWorkbenchSource).toContain('class="advertising-detail-budget-row"')
    expect(detailWorkbenchSource).toContain('class="advertising-detail-budget-item"')
    expect(detailWorkbenchSource).toContain('class="advertising-detail-budget-balance"')
    expect(detailWorkbenchSource).toContain('class="advertising-detail-budget-separator"')
    expect(detailWorkbenchSource).toContain('class="advertising-detail-budget-actions"')
    expect(detailWorkbenchSource).toContain('<a-switch v-model="budgetAutoTopUpEnabled" />')
    expect(detailWorkbenchSource).not.toContain(':model-value="campaign.budgetStatus === \'healthy\'"')
    expect(detailWorkbenchSource).toMatch(/预算余额[\s\S]*class="advertising-detail-budget-separator"[\s\S]*总预算[\s\S]*class="advertising-detail-budget-separator"[\s\S]*自动补充预算/)
    expect(detailWorkbenchSource).not.toContain('class="advertising-detail-back-row"')
    expect(detailWorkbenchSource).not.toContain('class="advertising-page-header advertising-detail-header"')
    expect(detailWorkbenchSource).not.toContain('class="advertising-detail-budget-card"')
    expect(detailWorkbenchSource).toContain('预算余额')
    expect(detailWorkbenchSource).toContain('自动补充预算')
    expect(detailWorkbenchSource).toContain('class="advertising-statistics-section advertising-detail-module-section"')
    expect(detailWorkbenchSource).toContain('class="advertising-statistics-heading"')
    expect(detailWorkbenchSource).toContain('class="advertising-statistics-title-group"')
    expect(detailWorkbenchSource).not.toContain('class="advertising-statistics-chart-switch"')
    expect(detailWorkbenchSource).not.toContain('<a-switch model-value size="small" />')
    expect(detailWorkbenchSource).not.toContain('<span>图表</span>')
    expect(detailWorkbenchSource).toContain('class="advertising-statistics-actions"')
    expect(detailWorkbenchSource).toContain('<a-range-picker v-model="selectedDetailDateRange" value-format="YYYY-MM-DD" />')
    expect(detailWorkbenchSource).toContain('v-for="card in detailStatisticCards"')
    expect(detailWorkbenchSource).toContain(':style="{ \'--advertising-kpi-color\': card.color }"')
    expect(detailWorkbenchSource).toContain(':aria-pressed="selectedDetailMetrics.includes(card.metricKey)"')
    expect(detailWorkbenchSource).toContain(':class="{ \'is-active\': selectedDetailMetrics.includes(card.metricKey) }"')
    expect(detailWorkbenchSource).toContain('@click="toggleDetailMetric(card.metricKey)"')
    expect(detailWorkbenchSource).toContain('class="advertising-kpi-card-label"')
    expect(detailWorkbenchSource).toContain('class="advertising-kpi-card-main"')
    expect(detailWorkbenchSource).toContain(':class="`is-${card.trend}`"')
    expect(detailWorkbenchSource).not.toContain('class="advertising-kpi-avatar"')
    expect(detailWorkbenchSource).not.toContain('class="advertising-kpi-card-submetrics"')
    expect(detailWorkbenchSource).toContain('class="advertising-chart-stage"')
    expect(detailWorkbenchSource).not.toContain('v-model="selectedDetailMetric"')
    expect(detailWorkbenchSource).toContain('class="advertising-chart-card advertising-chart-frame"')
    expect(detailWorkbenchSource).toContain('<AppEChart')
    expect(detailWorkbenchSource).toContain('class="advertising-e-chart"')
    expect(detailWorkbenchSource).toContain(':option="detailChartOption"')
    expect(detailWorkbenchSource).not.toContain('<svg class="advertising-chart-svg"')
    expect(detailWorkbenchSource).toContain('class="advertising-products-section advertising-detail-module-section"')
    expect(detailWorkbenchSource).toContain('完整统计')
    expect(detailWorkbenchSource).toContain('filterAdvertisingProductClusters')
    expect(detailWorkbenchSource).toContain('搜索词集群')
    expect(detailWorkbenchSource).toContain('推荐商品')
    expect(detailWorkbenchSource).toContain('expandedProductIds')
    expect(detailWorkbenchSource).toContain('<a-modal')
    expect(detailWorkbenchSource).toContain('v-model:visible="editNameVisible"')
    expect(detailWorkbenchSource).toContain(':on-before-ok="saveCampaignName"')
    expect(detailWorkbenchSource).toContain('<a-drawer')
    expect(detailWorkbenchSource).toContain('v-model:visible="historyVisible"')
  })

  it('renders advertising detail products as a table', () => {
    expect(detailWorkbenchSource).not.toContain("import ConfigurableDataTable from '../common/ConfigurableDataTable.vue'")
    expect(detailWorkbenchSource).not.toContain("import type { ConfigurableTableColumn } from '../../data/configurableTable'")
    expect(detailWorkbenchSource).toContain("import AppDataTable from '../common/AppDataTable.vue'")
    expect(detailWorkbenchSource).toContain("import { useProductCatalogStore } from '../../data/productCatalog'")
    expect(detailWorkbenchSource).toContain('const catalogStore = useProductCatalogStore()')
    expect(detailWorkbenchSource).toContain('const productBySku = computed')
    expect(detailWorkbenchSource).toContain('const getAdvertisingProductName = (product?: AdvertisingCampaignProduct)')
    expect(detailWorkbenchSource).toContain('const getAdvertisingProductBrand = (product?: AdvertisingCampaignProduct)')
    expect(detailWorkbenchSource).toContain('const getAdvertisingProductImage = (product?: AdvertisingCampaignProduct)')
    expect(detailWorkbenchSource).not.toContain('productVisibleColumnKeys')
    expect(detailWorkbenchSource).toContain('const productColumns: TableColumnData[] = [')
    expect(detailWorkbenchSource).toContain("{ title: '图片', dataIndex: 'image', slotName: 'image', width: 72")
    expect(detailWorkbenchSource).toContain("{ title: '名称 · 品牌 · SKU', dataIndex: 'sku', slotName: 'product', minWidth: 260")
    expect(detailWorkbenchSource).not.toContain("{ title: '名称 · 品牌 · SKU', dataIndex: 'sku', slotName: 'product', width: 520")
    expect(detailWorkbenchSource).not.toContain("{ title: '商品', dataIndex: 'sku', slotName: 'product'")
    expect(detailWorkbenchSource).not.toContain("{ title: 'SKU', dataIndex: 'sku', slotName: 'sku'")
    expect(detailWorkbenchSource).toContain("{ title: '出价 (CPM)', dataIndex: 'bid', slotName: 'bid', width: 152")
    expect(detailWorkbenchSource).not.toContain("{ title: '投放位置', dataIndex: 'placement'")
    expect(detailWorkbenchSource).not.toContain('const getProductPlacement =')
    expect(detailWorkbenchSource).not.toContain('<ConfigurableDataTable')
    expect(detailWorkbenchSource).toContain('<AppDataTable')
    expect(detailWorkbenchSource).toContain('class="advertising-products-table-shell"')
    expect(detailWorkbenchSource).not.toMatch(/<div class="advertising-products-table-shell">\s*<a-table/)
    expect(detailWorkbenchSource).toContain('class="advertising-products-table"')
    expect(detailWorkbenchSource).toContain('wrapper-class="advertising-products-table-shell"')
    expect(detailWorkbenchSource).toContain('table-class="advertising-products-table"')
    expect(detailWorkbenchSource).toContain('highlight-column-on-header-hover')
    expect(detailWorkbenchSource).toContain(':columns="productColumns"')
    expect(detailWorkbenchSource).toContain('const productTableScroll = { x: 620 }')
    expect(detailWorkbenchSource).toContain(':scroll="productTableScroll"')
    expect(detailWorkbenchSource).not.toContain(':scroll="{ x: 908 }"')
    expect(detailWorkbenchSource).toContain(':data="campaign.products"')
    expect(detailWorkbenchSource).toContain('v-model:expanded-keys="expandedProductIds"')
    expect(detailWorkbenchSource).toContain(':row-class="getProductRowClass"')
    expect(detailWorkbenchSource).toContain("const getProductRowClass = (record: AdvertisingCampaignProduct) =>")
    expect(detailWorkbenchSource).toContain("expandedProductIds.value.includes(record.id) ? 'is-expanded-product-row' : ''")
    expect(detailWorkbenchSource).not.toContain(':expandable="{ width: 44 }"')
    expect(detailWorkbenchSource).not.toContain('@expanded-change="handleProductExpandedChange"')
    expect(detailWorkbenchSource).toContain('const toggleExpandedProduct = (productId: string) =>')
    expect(detailWorkbenchSource).toContain('expandedProductIds.value.filter((expandedProductId) => expandedProductId !== productId)')
    expect(detailWorkbenchSource).toContain('expandedProductIds.value = [...expandedProductIds.value, productId]')
    expect(detailWorkbenchSource).not.toContain('expandedProductIds.value.includes(productId) ? [] : [productId]')
    expect(detailWorkbenchSource).toContain("{ title: '操作', slotName: 'operation', width: 136, minWidth: 124, align: 'center' }")
    expect(detailWorkbenchSource).toContain('<template #image="{ record }">')
    expect(detailWorkbenchSource).toContain('<template #product="{ record }">')
    expect(detailWorkbenchSource).toContain('{{ getAdvertisingProductBrand(record) }} · {{ record.sku }}')
    expect(detailWorkbenchSource).toContain('<strong>{{ getAdvertisingProductName(record) }}</strong>')
    expect(detailWorkbenchSource).not.toContain('{{ campaign.platform }} · {{ campaign.storeName }}')
    expect(detailWorkbenchSource).toContain('<template #bid="{ rowIndex }">')
    expect(detailWorkbenchSource).toContain('class="advertising-products-bid-text"')
    expect(detailWorkbenchSource).toContain('{{ getProductBid(rowIndex) }}</span>')
    expect(detailWorkbenchSource).not.toContain('class="advertising-products-bid-card"')
    expect(detailWorkbenchSource).not.toContain('<strong>{{ getProductBid(rowIndex) }}</strong>')
    expect(detailWorkbenchSource).not.toContain('<span>顶级支架</span>')
    expect(detailWorkbenchSource).not.toContain('class="advertising-products-table-number"')
    expect(detailWorkbenchSource).not.toContain('<template #placement=')
    expect(detailWorkbenchSource).toContain('<template #operation="{ record }">')
    expect(detailWorkbenchSource).toContain('class="advertising-product-expand-button"')
    expect(detailWorkbenchSource).toContain('@click="toggleExpandedProduct(record.id)"')
    expect(detailWorkbenchSource).toContain('<icon-up v-if="expandedProductIds.includes(record.id)" />')
    expect(detailWorkbenchSource).toContain('<icon-down v-else />')
    expect(detailWorkbenchSource).toContain('<template #expand-row="{ record }">')
    expect(detailWorkbenchSource).toContain('class="advertising-expanded-tabs"')
    expect(detailWorkbenchSource).toContain('type="line"')
    expect(detailWorkbenchSource).not.toMatch(/<a-tabs[\s\S]*class="advertising-expanded-tabs"[\s\S]*size="mini"/)
    expect(detailWorkbenchSource).toContain('class="advertising-cluster-state-tabs"')
    expect(detailWorkbenchSource).toContain('v-model:active-key="clusterFilter"')
    expect(detailWorkbenchSource).toContain("const clusterFilter = ref<ClusterFilterValue>('all')")
    expect(detailWorkbenchSource).toContain('type="rounded"')
    expect(detailWorkbenchSource).toMatch(/<a-tab-pane key="all" title="全部" \/>[\s\S]*?<a-tab-pane key="active" title="活跃" \/>[\s\S]*?<a-tab-pane key="inactive" title="不活跃" \/>/)
    expect(detailWorkbenchSource).not.toContain('<a-radio value="active">活跃</a-radio>')
    expect(detailWorkbenchSource).not.toContain('class="advertising-cluster-search-row"')
    expect(detailWorkbenchSource).not.toContain('<a-checkbox />')
    expect(detailWorkbenchSource).not.toContain('clusterKeyword')
    expect(detailWorkbenchSource).not.toContain('placeholder="寻找"')
    expect(detailWorkbenchSource).toContain('const clusterTableScroll = { x: 1110 }')
    expect(detailWorkbenchSource).toContain("{ title: '平均排名', dataIndex: 'rank', slotName: 'rank', width: 110, align: 'right' }")
    expect(detailWorkbenchSource).toContain(':scroll="clusterTableScroll"')
    expect(detailWorkbenchSource).toContain('class="advertising-cluster-table"')
    expect(detailWorkbenchSource).not.toContain('const recommendedProductColumns: TableColumnData[] = [')
    expect(detailWorkbenchSource).not.toContain('advertising-recommended-table')
    expect(detailWorkbenchSource).not.toContain(':columns="recommendedProductColumns"')
    expect(detailWorkbenchSource).toContain('class="advertising-recommended-products"')
    expect(detailWorkbenchSource).toContain('v-for="recommendedProduct in getRecommendedProducts(record.id)"')
    expect(detailWorkbenchSource).toContain(':key="recommendedProduct.id"')
    expect(detailWorkbenchSource).toContain('class="advertising-recommended-product"')
    expect(detailWorkbenchSource).toContain('getAdvertisingProductName(recommendedProduct)')
    expect(detailWorkbenchSource).toContain('getAdvertisingProductBrand(recommendedProduct)')
    expect(detailWorkbenchSource).toContain('recommendedProduct.searchClusters.length')
    expect(detailWorkbenchSource).not.toContain('{{ campaign.products.length }} 个商品')
    expect(detailWorkbenchSource).not.toContain('class="advertising-product-list"')
    expect(detailWorkbenchSource).not.toContain('class="advertising-product-card"')
    expect(styleSource).toContain('.advertising-products-table')
    expect(styleSource).toContain('.advertising-products-table-product')
    expect(styleSource).toContain('.advertising-products-bid-text')
    expect(styleSource).toMatch(/\.advertising-operation-actions\s*{[^}]*display: inline-flex;[^}]*justify-content: center;/s)
    expect(styleSource).toMatch(/\.advertising-products-table \.advertising-product-actions\s*{[^}]*display: inline-flex;[^}]*min-width: max-content;[^}]*justify-content: center;[^}]*gap: 4px;[^}]*flex-wrap: nowrap;/s)
    expect(styleSource).toMatch(/\.advertising-products-bid-text\s*{[^}]*color: #165dff;[^}]*font-variant-numeric: tabular-nums;/s)
    expect(styleSource).not.toContain('.advertising-products-bid-card')
    expect(styleSource).not.toContain('background: #165dff')
    expect(styleSource).not.toContain('background: #8f3cff')
    expect(styleSource).toMatch(/\.advertising-products-table \.arco-table-th\s*{[^}]*background: var\(--advertising-color-fill\);/s)
    expect(styleSource).toMatch(/\.advertising-products-table \.arco-table-td\s*{[^}]*background: var\(--advertising-color-surface\);/s)
    expect(styleSource).toMatch(/\.advertising-products-table > \.arco-spin > \.arco-table-container > \.arco-scrollbar > \.arco-table-content > \.arco-table-element > tbody > \.arco-table-tr:not\(\.arco-table-tr-expand\):hover > \.arco-table-td\s*{[^}]*background: var\(--advertising-color-hover-bg\);/s)
    expect(styleSource).toMatch(/\.advertising-products-table\.arco-table-hover > \.arco-spin > \.arco-table-container > \.arco-scrollbar > \.arco-table-content > \.arco-table-element > tbody > \.arco-table-tr-expand:hover > \.arco-table-td:not\(\.arco-table-col-fixed-left\):not\(\.arco-table-col-fixed-right\)\s*{[^}]*background: var\(--advertising-color-surface\);[^}]*background-color: var\(--advertising-color-surface\);/s)
    expect(styleSource).toMatch(/\.advertising-products-table\.arco-table-hover > \.arco-spin > \.arco-table-container > \.arco-scrollbar > \.arco-table-content > \.arco-table-element > tbody > \.arco-table-tr-expand:hover \.advertising-cluster-table \.arco-table-td\s*{[^}]*background: var\(--advertising-color-surface\);[^}]*background-color: var\(--advertising-color-surface\);/s)
    expect(styleSource).not.toContain('.advertising-products-table .arco-table-tr:hover .arco-table-td')
    expect(styleSource).toMatch(/\.advertising-products-table tbody > \.arco-table-tr:not\(\.arco-table-tr-expand\) > \.arco-table-td > \.arco-table-cell\s*{[^}]*padding-top: 10px;[^}]*padding-bottom: 10px;/s)
    expect(styleSource).toMatch(/\.advertising-products-table \.is-expanded-product-row > \.arco-table-td\s*{[^}]*border-bottom: 0;/s)
    expect(styleSource).toMatch(/\.advertising-products-table-shell \.arco-table-tr-expand > \.arco-table-td\s*{[^}]*padding: 0;[^}]*border-top: 0;[^}]*background: var\(--advertising-color-surface\);/s)
    expect(styleSource).toMatch(/\.advertising-product-expanded\s*{[^}]*position: relative;[^}]*min-width: 0;[^}]*max-width: 100%;[^}]*overflow: hidden;[^}]*padding: 28px 12px 30px;[^}]*border: 0;[^}]*background: var\(--advertising-color-surface\);/s)
    expect(styleSource).not.toContain('box-shadow: inset 0 1px 0 var(--advertising-color-border);')
    expect(styleSource).toMatch(/\.advertising-product-expanded::before\s*{[^}]*top: 0;[^}]*right: 12px;[^}]*left: 12px;[^}]*height: 1px;[^}]*background: var\(--advertising-color-border\);/s)
    expect(styleSource).toMatch(/\.advertising-expanded-tabs\s*{[^}]*min-width: 260px;/s)
    expect(styleSource).toMatch(/\.advertising-expanded-tabs \.arco-tabs-tab\s*{[^}]*font-weight: 500;/s)
    expect(styleSource).not.toContain('.advertising-expanded-tabs .arco-tabs-tab {\n  color: var(--advertising-color-text);\n  font-size: 13px;')
    expect(styleSource).toMatch(/\.advertising-cluster-state-tabs\s*{[^}]*width: fit-content;[^}]*min-height: 32px;[^}]*overflow: visible;/s)
    expect(styleSource).toMatch(/\.advertising-cluster-state-tabs \.arco-tabs-nav\s*{[^}]*margin: 0;[^}]*overflow: visible;/s)
    expect(styleSource).toMatch(/\.advertising-cluster-state-tabs \.arco-tabs-nav-type-rounded \.arco-tabs-nav-tab\s*{[^}]*min-height: 32px;[^}]*overflow: visible;[^}]*line-height: 20px;[^}]*font-size: 13px;/s)
    expect(styleSource).not.toMatch(/\.advertising-cluster-state-tabs \.arco-tabs-nav-type-rounded \.arco-tabs-nav-tab\s*{[^}]*height: 28px;/s)
    expect(styleSource).not.toContain('.advertising-cluster-state-tabs .arco-radio-button')
    expect(styleSource).toMatch(/\.advertising-cluster-table\s*{[^}]*width: 100%;[^}]*max-width: 100%;[^}]*min-width: 0;[^}]*overflow: hidden;[^}]*margin: 2px 0 0;/s)
    expect(styleSource).toMatch(/\.advertising-products-table-shell \.arco-table-tr-expand \.arco-table-td \.advertising-cluster-table\s*{[^}]*margin: 2px 0 0;/s)
    expect(styleSource).toMatch(/\.advertising-cluster-table \.arco-table-container\s*{[^}]*max-width: 100%;[^}]*border: 0;/s)
    expect(styleSource).toMatch(/\.advertising-cluster-table tbody > \.arco-table-tr:hover > \.arco-table-td\s*{[^}]*background: var\(--advertising-color-hover-bg\);[^}]*background-color: var\(--advertising-color-hover-bg\);/s)
    expect(styleSource).toMatch(/\.advertising-recommended-products\s*{[^}]*display: flex;[^}]*flex-direction: column;[^}]*gap: 10px;/s)
    expect(styleSource).toMatch(/\.advertising-recommended-product\s*{[^}]*display: grid;[^}]*grid-template-columns: minmax\(220px, 1fr\) minmax\(80px, auto\) auto;[^}]*background: var\(--advertising-color-fill\);/s)
  })

  it('adds pagination to the expanded search cluster table', () => {
    expect(detailWorkbenchSource).toContain('const clusterCurrentPage = ref(1)')
    expect(detailWorkbenchSource).toContain('const clusterPageSize = ref(10)')
    expect(detailWorkbenchSource).toContain('const getPagedProductClusters = (clusters: AdvertisingSearchCluster[]) =>')
    expect(detailWorkbenchSource).toContain(':data="getPagedProductClusters(record.searchClusters)"')
    expect(detailWorkbenchSource).toMatch(/<div class="advertising-cluster-pagination">[\s\S]*?<a-pagination[\s\S]*?v-model:current="clusterCurrentPage"[\s\S]*?v-model:page-size="clusterPageSize"[\s\S]*?:total="filterProductClusters\(record.searchClusters\).length"[\s\S]*?show-total[\s\S]*?show-jumper[\s\S]*?show-page-size/)
    expect(styleSource).toMatch(/\.advertising-cluster-pagination\s*\{[^}]*display: flex;[^}]*justify-content: flex-end;/s)
  })

  it('renders the advertising statistics shell', () => {
    expect(statisticsWorkbenchSource).toContain('活动统计')
    expect(statisticsWorkbenchSource).toContain('selectedMetrics')
    expect(statisticsWorkbenchSource).toContain("import type { EChartsOption } from 'echarts'")
    expect(statisticsWorkbenchSource).toContain("import type { TableColumnData } from '@arco-design/web-vue'")
    expect(statisticsWorkbenchSource).toContain("import AppEChart from '../common/AppEChart.vue'")
    expect(statisticsWorkbenchSource).toContain("import AppDataTable from '../common/AppDataTable.vue'")
    expect(statisticsWorkbenchSource).toContain('createAdvertisingProductStatisticsRows')
    expect(statisticsWorkbenchSource).toContain('const statisticsMetricCards = computed<StatisticsMetricCard[]>(() =>')
    expect(statisticsWorkbenchSource).toContain('const statisticsProductColumns: TableColumnData[] = [')
    expect(statisticsWorkbenchSource).toContain('const expandedStatisticsProductGroupIds = ref<string[]>([])')
    expect(statisticsWorkbenchSource).toContain('const statisticsProductCurrentPage = ref(1)')
    expect(statisticsWorkbenchSource).toContain('const statisticsProductPageSize = ref(10)')
    expect(statisticsWorkbenchSource).toContain('const statisticsProductRows = computed(() =>')
    expect(statisticsWorkbenchSource).toContain('const visibleStatisticsProductRows = computed(() =>')
    expect(statisticsWorkbenchSource).toContain('const pagedStatisticsProductRows = computed(() =>')
    expect(statisticsWorkbenchSource).toContain('const toggleStatisticsProductExpansion = (rowId: string) =>')
    expect(statisticsWorkbenchSource).toContain('const statisticsChartOption = computed<EChartsOption>(() =>')
    expect(statisticsWorkbenchSource).toContain("const statisticsChartUpdateOptions = { replaceMerge: ['series', 'xAxis', 'yAxis', 'dataZoom'] }")
    expect(statisticsWorkbenchSource).not.toContain('createStatisticPolylinePoints')
    expect(statisticsWorkbenchSource).toContain('广告活动的基本统计')
    expect(statisticsWorkbenchSource).toContain('扩展统计')
    expect(statisticsWorkbenchSource).toContain('class="advertising-statistics-section advertising-statistics-page-section advertising-detail-module-section"')
    expect(statisticsWorkbenchSource).toContain('class="advertising-kpi-grid advertising-statistics-page-kpi-grid"')
    expect(statisticsWorkbenchSource).toContain('class="advertising-chart-card advertising-chart-frame advertising-statistics-page-chart-frame"')
    expect(statisticsWorkbenchSource).toContain('class="advertising-products-section advertising-statistics-products advertising-detail-module-section"')
    expect(statisticsWorkbenchSource).not.toContain('{{ campaign.products.length }} 个商品')
    expect(statisticsWorkbenchSource).toContain('<AppDataTable')
    expect(statisticsWorkbenchSource).toContain(':columns="statisticsProductColumns"')
    expect(statisticsWorkbenchSource).toContain(':data="pagedStatisticsProductRows"')
    expect(statisticsWorkbenchSource).not.toContain('v-model:expanded-keys="expandedStatisticsProductIds"')
    expect(statisticsWorkbenchSource).toContain('wrapper-class="advertising-statistics-table-wrap"')
    expect(statisticsWorkbenchSource).toContain('table-class="advertising-statistics-table"')
    expect(statisticsWorkbenchSource).toContain("row-key=\"displayId\"")
    expect(statisticsWorkbenchSource).not.toContain('<template #expand-row="{ record }">')
    expect(statisticsWorkbenchSource).toContain('还有 {{ record.productCount - 1 }} 件商品')
    expect(statisticsWorkbenchSource).toContain("record.rowType === 'group'")
    expect(statisticsWorkbenchSource).toContain("record.rowType === 'item'")
    expect(statisticsWorkbenchSource).toContain("expandedStatisticsProductGroupIds.includes(record.id)")
    expect(statisticsWorkbenchSource).toContain('<div class="advertising-statistics-pagination">')
    expect(statisticsWorkbenchSource).toContain('v-model:current="statisticsProductCurrentPage"')
    expect(statisticsWorkbenchSource).toContain('v-model:page-size="statisticsProductPageSize"')
    expect(statisticsWorkbenchSource).toContain(':total="visibleStatisticsProductRows.length"')
    expect(statisticsWorkbenchSource).not.toContain('<table class="advertising-statistics-table">')
    expect(statisticsWorkbenchSource).toContain('<AppEChart')
    expect(statisticsWorkbenchSource).toContain(':option="statisticsChartOption"')
    expect(statisticsWorkbenchSource).toContain(':update-options="statisticsChartUpdateOptions"')
    expect(statisticsWorkbenchSource).not.toContain('<svg class="advertising-chart-svg"')
    expect(styleSource).toMatch(/\.advertising-statistics-page-section\s*{[^}]*padding: 0;/s)
    expect(styleSource).toMatch(/\.advertising-statistics-page-kpi-grid\s*{[^}]*grid-template-columns: repeat\(5, minmax\(0, 1fr\)\);/s)
    expect(styleSource).toMatch(/\.advertising-statistics-page-chart-frame\s*{[^}]*padding-top: 22px;/s)
    expect(styleSource).toMatch(/\.advertising-statistics-product-expand-link\s*{[^}]*height: 22px;[^}]*padding: 0;/s)
    expect(styleSource).toMatch(/\.advertising-statistics-table \.arco-table-tr\.is-statistics-product-child > \.arco-table-td\s*{[^}]*background: var\(--advertising-color-fill\);[^}]*background-color: var\(--advertising-color-fill\);/s)
    expect(styleSource).not.toContain('.advertising-statistics-expanded-product')
    expect(styleSource).toMatch(/\.advertising-statistics-pagination\s*{[^}]*display: flex;[^}]*justify-content: flex-end;/s)
  })

  it('scopes chart svg sizing away from table and checkbox icons', () => {
    expect(detailWorkbenchSource).toContain('<AppEChart')
    expect(detailWorkbenchSource).not.toContain('<svg class="advertising-chart-svg"')
    expect(statisticsWorkbenchSource).toContain('<AppEChart')
    expect(statisticsWorkbenchSource).not.toContain('<svg class="advertising-chart-svg"')
    expect(styleSource).toContain('.advertising-chart-svg')
    expect(styleSource).not.toContain('.advertising-chart-card svg')
    expect(styleSource).not.toContain('.advertising-statistics-chart svg')
  })

  it('adds advertising styles', () => {
    [
      '.store-advertising-workbench',
      '.advertising-page-header',
      '.advertising-status-toggle-cell',
      '.advertising-status-toggle-cell .arco-switch',
      '.advertising-campaign-main',
      '.advertising-campaign-thumb-badge',
      '.advertising-campaign-thumb-badge .arco-badge-number',
      '.advertising-table-footer-row',
      '.advertising-bulk-action-bar',
      '.advertising-bulk-action-placeholder',
      '.advertising-pagination',
      '.store-advertising-table',
      '.store-advertising-campaign-table .arco-table-th',
      '.store-advertising-campaign-table .arco-table-td',
      '.store-advertising-campaign-table:not(.is-auto-wrap) .advertising-link-button',
      '.store-advertising-campaign-table:not(.is-auto-wrap) .advertising-campaign-meta',
      '.advertising-detail-overview-card',
      '.advertising-detail-overview-main',
      '.advertising-detail-overview-profile',
      '.advertising-detail-overview-thumb',
      '.advertising-detail-overview-identity',
      '.advertising-detail-overview-title-row',
      '.advertising-detail-overview-description',
      '.advertising-detail-title-edit-button',
      '.advertising-detail-meta-row',
      '.advertising-detail-meta-id',
      '.advertising-detail-id-copy-button',
      '.advertising-detail-history-button',
      '.advertising-detail-overview-actions',
      '.advertising-detail-overview-divider',
      '.advertising-detail-budget-row',
      '.advertising-detail-budget-item',
      '.advertising-detail-budget-balance',
      '.advertising-detail-budget-separator',
      '.advertising-detail-budget-actions',
      '.advertising-detail-name-form',
      '.advertising-detail-history-list',
      '.advertising-statistics-heading',
      '.advertising-statistics-title-group',
      '.advertising-statistics-actions',
      '.advertising-kpi-card.is-active',
      '.advertising-kpi-card-label',
      '.advertising-kpi-card-main',
      '.advertising-kpi-delta',
      '.advertising-chart-stage',
      '.advertising-chart-frame',
      '.advertising-e-chart',
      '.advertising-product-expanded',
      '.advertising-statistics-workbench',
      '.advertising-chart-card',
      '.advertising-statistics-funnel',
      '.advertising-statistics-table',
    ].forEach((selector) => {
      expect(styleSource).toContain(selector)
    })
    expect(styleSource).toContain('--advertising-color-primary: rgb(var(--primary-6))')
    expect(styleSource).toContain('background: var(--color-fill-3)')
    expect(styleSource).toContain('font-size: 10px')
    expect(styleSource).toContain('height: 14px')
    expect(styleSource).toContain('flex-wrap: nowrap')
    expect(styleSource).toMatch(/\.advertising-status-toggle-cell\s*{[^}]*justify-content: center;/)
    expect(styleSource).toMatch(/\.advertising-campaign-main\s*{[^}]*gap: 14px;/)
    expect(styleSource).toMatch(/\.advertising-bulk-action-bar \.arco-btn\s*{[^}]*height: var\(--workspace-control-height, var\(--size-default, 32px\)\);[^}]*border-radius: var\(--border-radius-medium\);[^}]*padding: 0 15px;/)
    expect(styleSource).toMatch(/\.store-advertising-campaign-table \.arco-table-th\s*{[^}]*font-size: 13px;[^}]*font-weight: 600;/)
    expect(styleSource).toMatch(/\.store-advertising-campaign-table \.arco-table-td\s*{[^}]*font-size: 13px;[^}]*white-space: nowrap;/)
    expect(styleSource).toMatch(/\.advertising-link-button\s*{[^}]*font-size: 14px;[^}]*line-height: 24px;/)
    expect(styleSource).toMatch(/\.advertising-detail-title-edit-button\s*{[^}]*width: 28px;[^}]*height: 28px;[^}]*padding: 0;[^}]*color: var\(--color-text-1\);/s)
    expect(styleSource).toMatch(/\.advertising-detail-title-edit-button\.arco-btn-text,\s*\.advertising-detail-title-edit-button\.arco-btn-text:hover,\s*\.advertising-detail-title-edit-button\.arco-btn-text:focus,\s*\.advertising-detail-title-edit-button\.arco-btn-text:active\s*{[^}]*color: var\(--color-text-1\);/s)
    expect(styleSource).toMatch(/\.advertising-detail-title-edit-button \.arco-icon\s*{[^}]*color: var\(--color-text-1\);/s)
    expect(styleSource).toMatch(/\.advertising-detail-meta-row\s*{[^}]*display: flex;[^}]*align-items: center;[^}]*flex-wrap: wrap;/s)
    expect(styleSource).toMatch(/\.advertising-detail-id-copy-button\s*{[^}]*width: 22px;[^}]*height: 22px;[^}]*padding: 0;[^}]*color: var\(--color-text-3\);/s)
    expect(styleSource).toMatch(/\.advertising-detail-id-copy-button\.arco-btn-text,\s*\.advertising-detail-id-copy-button\.arco-btn-text:hover,\s*\.advertising-detail-id-copy-button\.arco-btn-text:focus,\s*\.advertising-detail-id-copy-button\.arco-btn-text:active\s*{[^}]*color: var\(--color-text-3\);/s)
    expect(styleSource).toMatch(/\.advertising-detail-id-copy-button \.arco-icon\s*{[^}]*color: var\(--color-text-3\);/s)
    expect(styleSource).toMatch(/\.advertising-detail-history-button\s*{[^}]*color: var\(--advertising-color-primary\);/s)
    expect(styleSource).toMatch(/\.advertising-detail-budget-row\s*{[^}]*display: flex;[^}]*justify-content: flex-start;[^}]*flex-wrap: wrap;/s)
    expect(styleSource).toMatch(/\.advertising-detail-budget-item \.advertising-detail-budget-balance\s*{[^}]*color: var\(--advertising-color-primary\);/s)
    expect(styleSource).toMatch(/\.advertising-detail-budget-separator\s*{[^}]*width: 1px;[^}]*height: 30px;[^}]*background: var\(--advertising-color-border\);/s)
    expect(styleSource).toMatch(/\.advertising-detail-budget-actions\s*{[^}]*justify-content: flex-start;/s)
    expect(styleSource).toMatch(/\.advertising-detail-module-section\s*{[^}]*gap: 0;[^}]*padding: 0;[^}]*border: 0;[^}]*border-radius: 0;[^}]*background: transparent;[^}]*box-shadow: none;/s)
    expect(styleSource).toMatch(/\.advertising-detail-module-section > \.advertising-statistics-heading,\s*\.advertising-detail-module-section > \.advertising-section-header\s*{[^}]*align-items: flex-start;[^}]*gap: 12px;[^}]*padding: 24px 0 8px;[^}]*border-bottom: 0;/s)
    expect(styleSource).toMatch(/\.advertising-detail-module-section > \.advertising-kpi-grid,\s*\.advertising-detail-module-section > \.advertising-products-table-shell\s*{[^}]*margin-top: 14px;/s)
    expect(styleSource).toMatch(/\.advertising-statistics-title-group h2\s*{[^}]*font-size: 16px;[^}]*line-height: 24px;/s)
    expect(styleSource).not.toContain('.advertising-statistics-chart-switch')
    expect(styleSource).toMatch(/\.advertising-kpi-grid\s*{[^}]*grid-template-columns: repeat\(4, minmax\(0, 1fr\)\);[^}]*gap: 0;[^}]*border-bottom: 1px solid var\(--advertising-color-border\);/s)
    expect(styleSource).toMatch(/\.advertising-kpi-card\s*{[^}]*cursor: pointer;[^}]*border-top: 1px solid var\(--advertising-color-border\);[^}]*background: var\(--advertising-color-surface\);/s)
    expect(styleSource).not.toContain('border-top: 2px solid transparent;')
    expect(styleSource).toMatch(/\.advertising-kpi-card:hover\s*{[^}]*background: var\(--advertising-color-bg\);/s)
    expect(styleSource).toMatch(/\.advertising-kpi-card\.is-active\s*{[^}]*--advertising-kpi-gradient-start: color-mix\(in srgb, var\(--advertising-kpi-color, var\(--advertising-color-primary\)\) 8%, transparent\);[^}]*--advertising-kpi-gradient-end: color-mix\(in srgb, var\(--advertising-kpi-color, var\(--advertising-color-primary\)\) 1\.5%, transparent\);[^}]*background: linear-gradient\(180deg, var\(--advertising-kpi-gradient-start\) 0%, var\(--advertising-kpi-gradient-end\) 100%\);[^}]*border-top-color: var\(--advertising-kpi-color, var\(--advertising-color-primary\)\);/s)
    expect(styleSource).toMatch(/\.advertising-kpi-card:focus-visible\s*{[^}]*outline: 1px solid var\(--advertising-kpi-color, var\(--advertising-color-primary\)\);/s)
    expect(styleSource).toMatch(/\.advertising-kpi-card \+ \.advertising-kpi-card\s*{[^}]*border-left: 1px solid var\(--advertising-color-border\);/s)
    expect(styleSource).toMatch(/\.advertising-kpi-card-main\s*{[^}]*align-items: center;[^}]*justify-content: space-between;[^}]*gap: 18px;/s)
    expect(styleSource).toMatch(/\.advertising-kpi-delta\s*{[^}]*margin-left: auto;[^}]*font-size: 14px;[^}]*line-height: 22px;/s)
    expect(styleSource).not.toContain('.advertising-kpi-delta.is-positive')
    expect(styleSource).not.toContain('.advertising-kpi-delta.is-negative')
    expect(styleSource).toMatch(/\.advertising-kpi-delta\.is-up\s*{[^}]*color: rgb\(var\(--success-6\)\);/s)
    expect(styleSource).toMatch(/\.advertising-kpi-delta\.is-down\s*{[^}]*color: rgb\(var\(--danger-6\)\);/s)
    expect(styleSource).toMatch(/\.advertising-kpi-delta\.is-flat\s*{[^}]*color: var\(--color-text-2\);/s)
    expect(styleSource).toMatch(/\.advertising-kpi-delta\.is-up::after\s*{[^}]*border-bottom: 7px solid currentColor;/s)
    expect(styleSource).toMatch(/\.advertising-kpi-delta\.is-flat::after\s*{[^}]*width: 8px;[^}]*height: 2px;[^}]*border: 0;[^}]*background: currentColor;/s)
    expect(styleSource).toMatch(/\.advertising-chart-stage\s*{[^}]*height: 340px;[^}]*overflow: hidden;/s)
    expect(styleSource).toMatch(/\.advertising-chart-frame\s*{[^}]*min-height: 320px;[^}]*border: 0;[^}]*background: transparent;/s)
    expect(styleSource).toMatch(/\.advertising-e-chart\s*{[^}]*width: 100%;/s)
    expect(styleSource).not.toContain('.advertising-status-pill')
    expect(styleSource).toContain('.advertising-chart-grid line')
    expect(styleSource).toContain('@media (max-width: 1199px)')
    expect(styleSource).toContain('@media (max-width: 767px)')
  })
})
